# Pandas 리마인드

### 실습 1 : 데이터 살펴보기

* Q0. 라이브러리 불러오기

In [1]:
import pandas as pd
import numpy

* Q1. pandas read_csv 함수를 이용하여 파일을 읽고, titanic 변수에 담습니다. 
    * 링크 : https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic.0.csv

In [21]:
titanic=pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic.0.csv")

* Q2. titanic의 shape를 확인합니다.

In [22]:
titanic.shape

(891, 12)

* Q3. titanic의 칼럼명과 각 칼럼의 데이터 타입을 확인합니다.

In [29]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [30]:
list(titanic.columns)

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [31]:
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [32]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

* Q4. titanic의 데이터의 첫 3행의 데이터와 마지막 3행의 데이터를 출력합니다.

In [24]:
titanic.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [25]:
titanic.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

* Q5. 기초 통계량을 조회합시다.

In [26]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

* Q6. titanic의 데이터를 'Fare' 칼럼을 기준으로 내림차순으로 정렬합니다.

In [33]:
titanic.sort_values('Fare',ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0000,NaN,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0000,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0000,NaN,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0000,NaN,S

* Q7. 운임('Fare')을 가장 많이 내고 탄 사람 10명을 조회하시오.

In [38]:
titanic.sort_values(['Fare'],ascending=False)['Name'].head(10)

258                         Ward, Miss. Anna
737                   Lesurer, Mr. Gustave J
679       Cardeza, Mr. Thomas Drake Martinez
88                Fortune, Miss. Mabel Helen
27            Fortune, Mr. Charles Alexander
341           Fortune, Miss. Alice Elizabeth
438                        Fortune, Mr. Mark
311               Ryerson, Miss. Emily Borie
742    Ryerson, Miss. Susan Parker "Suzette"
118                 Baxter, Mr. Quigg Edmond
Name: Name, dtype: object

### 실습 2 : 데이터 조회하기

* Q0. 라이브러리 불러오기

In [16]:
import pandas as pd
import numpy

* Q1. pandas read_csv 함수를 이용하여 파일을 읽고 boston 변수에 담습니다.

    * 링크 : https://raw.githubusercontent.com/DA4BAM/dataset/master/boston2.csv

In [17]:
boston=pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/boston2.csv")

In [18]:
boston.head()

,crim,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv,zn2
0,0.00632,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,1
1,0.02731,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,0
2,0.02729,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,0
3,0.03237,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4,0
4,0.06905,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,0

* Q2. boston의 shape를 확인합니다.

In [20]:
boston.shape

(506, 14)

* Q3. boston의 crim 변수를 Series 형태로 조회하시오.

In [50]:
#boston.crim
boston.loc[:,'crim']

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: crim, Length: 506, dtype: float64

In [51]:
boston.iloc[:,0] #인덱스 넘버로 정보 조회

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: crim, Length: 506, dtype: float64

* Q4. boston의 crim 변수를 DataFrame 형태로 조회하시오.

In [41]:
boston[['crim']]

        crim
0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
..       ...
501  0.06263
502  0.04527
503  0.06076
504  0.10959
505  0.04741

[506 rows x 1 columns]

In [52]:
boston.loc[:,['crim']]

        crim
0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
..       ...
501  0.06263
502  0.04527
503  0.06076
504  0.10959
505  0.04741

[506 rows x 1 columns]

In [53]:
boston.iloc[:,[0]]

        crim
0    0.00632
1    0.02731
2    0.02729
3    0.03237
4    0.06905
..       ...
501  0.06263
502  0.04527
503  0.06076
504  0.10959
505  0.04741

[506 rows x 1 columns]

* Q5. .loc을 이용하여 10행까지, 열은 crim, lstat, medv를 조회하시오.

In [56]:
#.loc[row,column]
#.iloc[row,column]
boston.loc[:9,['crim','lstat','medv']]

      crim  lstat  medv
0  0.00632   4.98  24.0
1  0.02731   9.14  21.6
2  0.02729   4.03  34.7
3  0.03237   2.94  33.4
4  0.06905   5.33  36.2
5  0.02985   5.21  28.7
6  0.08829  12.43  22.9
7  0.14455  19.15  27.1
8  0.21124  29.93  16.5
9  0.17004  17.10  18.9

* Q6. .iloc을 이용하여 Q5와 동일한 결과를 내시오.

In [59]:
boston.columns

Index(['crim', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv', 'zn2'],
      dtype='object')

In [62]:
#boston.iloc[:10,[0,11,12]]
boston.iloc[:,[0,11,12]][:10]

      crim  lstat  medv
0  0.00632   4.98  24.0
1  0.02731   9.14  21.6
2  0.02729   4.03  34.7
3  0.03237   2.94  33.4
4  0.06905   5.33  36.2
5  0.02985   5.21  28.7
6  0.08829  12.43  22.9
7  0.14455  19.15  27.1
8  0.21124  29.93  16.5
9  0.17004  17.10  18.9

In [58]:
boston.iloc[:10][['crim','lstat','medv']]

      crim  lstat  medv
0  0.00632   4.98  24.0
1  0.02731   9.14  21.6
2  0.02729   4.03  34.7
3  0.03237   2.94  33.4
4  0.06905   5.33  36.2
5  0.02985   5.21  28.7
6  0.08829  12.43  22.9
7  0.14455  19.15  27.1
8  0.21124  29.93  16.5
9  0.17004  17.10  18.9

### 실습 3 : 원하는 데이터 조회하기

* Q0. 라이브러리 불러오기

In [64]:
import pandas as pd

* Q1. 아래 링크에서 데이터를 읽어 boston으로 저장합니다.

    * https://raw.githubusercontent.com/DA4BAM/dataset/master/boston2.csv

In [65]:
boston=pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/boston2.csv")

* Q2. boston의 shape를 확인합니다.

In [66]:
boston.shape

(506, 14)

* Q3. boston의 칼럼명과 각 칼럼의 데이터 타입을 확인합니다.

In [67]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   indus    506 non-null    float64
 2   chas     506 non-null    int64
 3   nox      506 non-null    float64
 4   rm       506 non-null    float64
 5   age      506 non-null    float64
 6   dis      506 non-null    float64
 7   rad      506 non-null    int64
 8   tax      506 non-null    int64
 9   ptratio  506 non-null    float64
 10  black    506 non-null    float64
 11  lstat    506 non-null    float64
 12  medv     506 non-null    float64
 13  zn2      506 non-null    int64
dtypes: float64(10), int64(4)
memory usage: 55.5 KB

* Q4. unique 함수를 가지고 'zn2'의 칼럼에 들어있는 값의 종류를 확인합니다.

In [68]:
boston.zn2.unique()

array([1, 0, 2], dtype=int64)

* Q5. 타운들에 대해서 전체 평균 집값(medv)을 구하시오.

    * 평균 : .mean( )

In [72]:
mean=boston.medv.mean()
mean

22.532806324110698

* Q6. 찰스강변(chas == 1)이면서 집값(medv)이 전체 평균보다 낮은 데이터를 조회하시오.

In [92]:
#조건조회시 필요 loc
boston.loc[(boston['chas']==1) & (boston['medv']<mean),:]

,crim,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv,zn2
142,3.32105,19.58,1,0.871,5.403,100.0,1.3216,5,403,14.7,396.90,26.82,13.4,0
152,1.12658,19.58,1,0.871,5.012,88.0,1.6102,5,403,14.7,343.28,12.12,15.3,0
154,1.41385,19.58,1,0.871,6.129,96.0,1.7494,5,403,14.7,321.02,15.12,17.0,0
155,3.53501,19.58,1,0.871,6.152,82.6,1.7455,5,403,14.7,88.01,15.02,15.6,0
209,0.43571,10.59,1,0.489,5.344,100.0,3.8750,4,277,18.6,396.90,23.09,20.0,0
210,0.17446,10.59,1,0.489,5.960,92.1,3.8771,4,277,18.6,393.25,17.27,21.7,0
211,0.37578,10.59,1,0.489,5.404,88.6,3.6650,4,277,18.6,395.24,23.98,19.3,0
212,0.21719,10.59,1,0.489,5.807,53.8,3.6526,4,277,18.6,390.94,16.03,22.4,0
218,0.11069,13.89,1,0.550,5.951,93.8,2.8893,5,276,16.4,396.90,17.92,21.5,0
221,0.40771,6.20,1,0.507,6.164,91.3,3.0480,8,307,17.4,395.24,21.46,21.7,0
269,0.09065,6.96,1,0.464,5.920,61.5,3.9175,3,223,18.6,391.34,13.65,20.7,1
356,8.98296,18.10,1,0.770,6.212,97.4,2.1222,24,666,20.2,377.73,17.60,17.8,0
357,3.84970,18.10,1,0.770,6.395,91.0,2.5052,24,666,20.2,391.34,13.27,21.7,0
363,4.22239,18.10,1,0.770,5.803,89.0,1.9047,24,666,20.2,353.04,14.64,16.8,0
364,3.47428,18.10,1,0.718,8.780,82.9,1.9047,24,666,20.2,354.55,5.29,21.9,0

* Q7. 범죄율이 5% ~ 10% 사이의 데이터를 조회하시오.

In [94]:
boston.loc[boston['crim'].between(5,10),['crim']]
#boston.loc[(boston['crim']<10.0) & (boston['crim']>5.0)]

        crim
356  8.98296
358  5.20177
369  5.66998
370  6.53876
371  9.23230
372  8.26725
377  9.82349
382  9.18702
383  7.99248
389  8.15174
390  6.96215
391  5.29305
393  8.64476
395  8.71675
396  5.87205
397  7.67202
399  9.91655
402  9.59571
408  7.40389
421  7.02259
423  7.05042
424  8.79212
428  7.36711
429  9.33889
430  8.49213
432  6.44405
433  5.58107
439  9.39063
441  9.72418
442  5.66637
443  9.96654
446  6.28807
447  9.92485
448  9.32909
449  7.52601
450  6.71772
451  5.44114
452  5.09017
453  8.24809
454  9.51363
457  8.20058
458  7.75223
459  6.80117
462  6.65492
463  5.82115
464  7.83932
474  8.05579
475  6.39312
480  5.82401
481  5.70818
482  5.73116
486  5.69175

* Q8. titanic 데이터를 이용하여, 가장 비싼 운임을 내고 탄 사람을 조회하시오.

In [91]:
titanic.loc[titanic.Fare==titanic['Fare'].max()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

* Q9. titanic 데이터에서 객실등급 1등급이면서 20대인 남자 탑승객의 평균 운임을 구하시오

In [99]:
titanic[(titanic.Pclass==1) & (titanic.Age<30)&(titanic.Age>=20)&(titanic['Sex']=='male')]['Fare'].mean()

79.95948888888887

### 실습 4 : 데이터프레임 수정하기

* Q0. 라이브러리 불러오기

In [97]:
import pandas as pd

* Q1. 아래 링크를 titanic 변수에 저장하시오.

    * https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic.0.csv

In [135]:
titanic=pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic.0.csv")

* Q2. 연령대( (0,10], (10,20], (20,30], (30,40], (40,50], (50,100]) ) 칼럼을 추가하시오.

    * (0,10] : 0보다 크고, 10보다 작거나 같다.

In [136]:
titanic['Age2']=titanic['Age']//10*10

In [138]:
titanic['AgeGroup']='(0,10]'

In [139]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age2,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,20.0,"(0,10]"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,30.0,"(0,10]"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,20.0,"(0,10]"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,30.0,"(0,10]"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.0,"(0,10]"

In [140]:
titanic.loc[(titanic['Age']>10)&(titanic['Age']<20),'AgeGroup']='(10,20]'
titanic.loc[(titanic['Age']>20)&(titanic['Age']<30),'AgeGroup']='(20,30]'
titanic.loc[(titanic['Age']>30)&(titanic['Age']<40),'AgeGroup']='(30,40]'
titanic.loc[(titanic['Age']>40)&(titanic['Age']<50),'AgeGroup']='(40,50]'
titanic.loc[(titanic['Age']>50)&(titanic['Age']<100),'AgeGroup']='(50,100]'

In [141]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age2,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,20.0,"(20,30]"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,30.0,"(30,40]"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,20.0,"(20,30]"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,30.0,"(30,40]"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.0,"(30,40]"

* Q3. PassengerId, Name, SibSp, Parch, Ticket, Cabin 열을 삭제하시오.

In [142]:
titanic.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin'],axis=1,inplace=True)

* Q4. 성별(Sex) - male, female의 값을 m, f로 변경하시오.

In [143]:
titanic['Sex']=titanic['Sex'].map({'male':'m','female':'f'})

In [144]:
titanic.head()

   Survived  Pclass Sex   Age     Fare Embarked  Age2 AgeGroup
0         0       3   m  22.0   7.2500        S  20.0  (20,30]
1         1       1   f  38.0  71.2833        C  30.0  (30,40]
2         1       3   f  26.0   7.9250        S  20.0  (20,30]
3         1       1   f  35.0  53.1000        S  30.0  (30,40]
4         0       3   m  35.0   8.0500        S  30.0  (30,40]

### 실습 5 : Group by

* 타이타닉 데이터를 이용하시오

* Q1. 객실 등급별 평균 나이

In [145]:
titanic.groupby(by='Pclass',as_index=False)['Age'].mean()

   Pclass        Age
0       1  38.233441
1       2  29.877630
2       3  25.140620

* Q2. 승선 지역별 평균 운임

In [146]:
# as_index=False => df으로 나와라
titanic.groupby(by='Embarked',as_index=False)['Fare'].mean()

  Embarked       Fare
0        C  59.954144
1        Q  13.276030
2        S  27.079812

* Q3. 승선 지역별 생존 여부별 탑승객 수

In [147]:
titanic.groupby(by='Embarked',as_index=False)['Survived'].count()

  Embarked  Survived
0        C       168
1        Q        77
2        S       644

* Q4. 객실 등급별, 생존 여부별, 평균 운임, 최대 운임, 최소 운임

In [148]:
titanic.groupby(by=['Pclass','Survived'],as_index=False)['Fare'].agg(['mean','max','min'])

                      mean       max      min
Pclass Survived
1      0         64.684008  263.0000   0.0000
       1         95.608029  512.3292  25.9292
2      0         19.412328   73.5000   0.0000
       1         22.055700   65.0000  10.5000
3      0         13.669364   69.5500   0.0000
       1         13.694887   56.4958   0.0000