# Pandas 2 : 집계, 결합

## 환경준비 + 데이터 로드

* 라이브러리 불러오기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

* 데이터 로딩

In [2]:
# 데이터1 : 보스톤 타운별 집값
boston = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/boston2.csv")
boston.head()

,crim,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv,zn2
0,0.00632,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,1
1,0.02731,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,0
2,0.02729,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,0
3,0.03237,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4,0
4,0.06905,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,0

In [3]:
# 데이터2 : 타이타닉 승객 생존여부
titanic = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/titanic.0.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Dataframe 다루기

### 5.1 결합 1 : 조인 join(merge)

- 결합은 나눠어진 데이터셋으로 부터 하나로 모으는 작업입니다.

* 판다스에서 join은 굉장히 간단합니다.
* 자동으로 key를 잡아줍니다
* default로 inner join을 합니다.

In [4]:
sales = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/sales.csv")
products = pd.read_csv("https://raw.githubusercontent.com/DA4BAM/dataset/master/products.csv")

In [5]:
sales.head()

   OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
0      107    2  2016-01-02  p1036481    2  2100    c150417
1       69    1  2016-01-02  p1152861    1  1091    c212716
2       69    7  2016-01-02  p1013161    1  2600    c212716
3       69    8  2016-01-02  p1005771    1  1650    c212716
4       69   11  2016-01-02  p1089531    1  2600    c212716

In [6]:
products.head()

  ProductID ProductName Category SubCategory  CategoryOrd
0  p1052661         새우깡       간식          과자            3
1  p1054261       고구마스틱       간식          과자            3
2  p1097821          짱구       간식          과자            3
3  p1097831         감자칩       간식          과자            3
4  p1119071        뿌셔뿌셔       간식          과자            3

In [7]:
pd.merge(sales, products).head() # 공통된 칼럼이 있으면 그 칼럼을 key로 사용

,OrderID,Seq,OrderDate,ProductID,Qty,Amt,CustomerID,ProductName,Category,SubCategory,CategoryOrd
0,107,2,2016-01-02,p1036481,2,2100,c150417,순두부,반찬류,두부,1
1,137,4,2016-01-02,p1036481,2,2100,c280590,순두부,반찬류,두부,1
2,63,16,2016-01-03,p1036481,1,1050,c037915,순두부,반찬류,두부,1
3,135,3,2016-01-04,p1036481,3,3150,c100815,순두부,반찬류,두부,1
4,63,13,2016-01-06,p1036481,10,10500,c048405,순두부,반찬류,두부,1

how 파라미터에 값을 지정하여 outer join을 수행합니다.

how='inner'

==> left, right, outer

In [9]:
#공통된 칼럼이 있으면 그 칼럼을 key로 사용
pd.merge(sales, products, how='left').head()

,OrderID,Seq,OrderDate,ProductID,Qty,Amt,CustomerID,ProductName,Category,SubCategory,CategoryOrd
0,107,2,2016-01-02,p1036481,2,2100,c150417,순두부,반찬류,두부,1
1,69,1,2016-01-02,p1152861,1,1091,c212716,포토아이스크림,유제품,아이스크림,4
2,69,7,2016-01-02,p1013161,1,2600,c212716,느타리버섯,채소,버섯,5
3,69,8,2016-01-02,p1005771,1,1650,c212716,두부_소,반찬류,두부,1
4,69,11,2016-01-02,p1089531,1,2600,c212716,감자칩,채소,뿌리채소,5

### 실습 6 : Join(Merge) + groupby

* Q1. sales와 products를 ProductID 기준으로 merge하여 새로운 데이터프레임으로 저장합니다.

In [11]:
Product_df=pd.merge(sales,products,on='ProductID')

In [13]:
Product_df

,OrderID,Seq,OrderDate,ProductID,Qty,Amt,CustomerID,ProductName,Category,SubCategory,CategoryOrd
0,107,2,2016-01-02,p1036481,2,2100,c150417,순두부,반찬류,두부,1
1,137,4,2016-01-02,p1036481,2,2100,c280590,순두부,반찬류,두부,1
2,63,16,2016-01-03,p1036481,1,1050,c037915,순두부,반찬류,두부,1
3,135,3,2016-01-04,p1036481,3,3150,c100815,순두부,반찬류,두부,1
4,63,13,2016-01-06,p1036481,10,10500,c048405,순두부,반찬류,두부,1
...,...,...,...,...,...,...,...,...,...,...,...
70007,89,1,2017-03-31,p1299491,1,2150,c397789,당근,채소,뿌리채소,5
70008,69,5,2017-03-31,p1299491,1,2150,c268330,당근,채소,뿌리채소,5
70009,121,4,2017-03-31,p1299491,1,2150,c222461,당근,채소,뿌리채소,5
70010,159,9,2017-03-31,p1299491,1,2150,c275305,당근,채소,뿌리채소,5
70011,195,3,2017-03-31,p1299491,1,2150,c084130,당근,채소,뿌리채소,5

* Q2. Category별 총 매출액(amt)

In [45]:
Product_df.groupby(by='Category',as_index=False)["Amt"].sum()

  Category       Amt
0       간식  12920570
1       과일  49789339
2      반찬류  32204820
3      유제품  45261956
4       채소  54822783

* Q3. Category별 총 판매량 (qty)

In [46]:
Product_df.groupby(by='Category',as_index=False)["Amt"].count()

  Category    Amt
0       간식   7904
1       과일   6386
2      반찬류  16061
3      유제품  14145
4       채소  25516

* Q4. 전체에서 가장 매출이 높은 상품명 10개 조회

In [59]:
Product_df.groupby('ProductName',as_index=False)["Amt"].sum().sort_values('Amt',ascending='False').head(10)

   ProductName     Amt
47         초코콘  374057
4         낱개캔디  479197
27        소보루빵  536294
16      배아이스크림  623612
56     포토아이스크림  672267
0        감귤컵푸딩  677154
54        팽이버섯  691947
53      팥아이스크림  759973
34          양파  762702
55       포도컵푸딩  777637

### 5.3 결합 2 : 붙이기  concat( )

* 방금 전 실습에서 2,3번의 결과를 각각 dataframe으로 저장하시오.

In [61]:
data=pd.merge(sales,products,on='ProductID')

In [62]:
data2 = data.groupby('Category', as_index=False)['Amt'].sum()
data3 = data.groupby('Category', as_index=False)['Qty'].sum()

* 위 아래로 붙이기

In [63]:
pd.concat([data2, data3])

  Category         Amt      Qty
0       간식  12920570.0      NaN
1       과일  49789339.0      NaN
2      반찬류  32204820.0      NaN
3      유제품  45261956.0      NaN
4       채소  54822783.0      NaN
0       간식         NaN  12130.0
1       과일         NaN   6786.0
2      반찬류         NaN  20210.0
3      유제품         NaN  19731.0
4       채소         NaN  27859.0

* 옆으로 붙이기

In [64]:
pd.concat([data2, data3], axis=1)

  Category       Amt Category    Qty
0       간식  12920570       간식  12130
1       과일  49789339       과일   6786
2      반찬류  32204820      반찬류  20210
3      유제품  45261956      유제품  19731
4       채소  54822783       채소  27859

### 실습 7. concat( )

* Q1. 2016년 1월 데이터를 가진 데이터프레임과 2017년 1월 데이터를 가진 데이터프레임을 만드시오.

In [77]:
sales[['OrderDate']]

        OrderDate
0      2016-01-02
1      2016-01-02
2      2016-01-02
3      2016-01-02
4      2016-01-02
...           ...
70007  2017-03-31
70008  2017-03-31
70009  2017-03-31
70010  2017-03-31
70011  2017-03-31

[70012 rows x 1 columns]

In [79]:
sales_2016=sales[sales['OrderDate'].between("2016-01-01","2016-01-31")]

In [86]:
sales_2016.head()

   OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
0      107    2  2016-01-02  p1036481    2  2100    c150417
1       69    1  2016-01-02  p1152861    1  1091    c212716
2       69    7  2016-01-02  p1013161    1  2600    c212716
3       69    8  2016-01-02  p1005771    1  1650    c212716
4       69   11  2016-01-02  p1089531    1  2600    c212716

In [81]:
sales_2017=sales[sales['OrderDate'].between("2017-01-01","2017-01-31")]

In [89]:
sales_2017.tail()

       OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
60649      105   19  2017-01-31  p1089531    1  2500    c217725
60650      105   24  2017-01-31  p1133371    2  2000    c217725
60651      105   26  2017-01-31  p1100371    5  1600    c217725
60652      107    1  2017-01-31  p1207281    1  3300    c234291
60653      107    2  2017-01-31  p1100371    1   400    c234291

* Q2. Q1에서 만든 데이터프레임을 위, 아래로 붙이시오.

In [85]:
pd.concat([sales_2016,sales_2017],axis=0)

       OrderID  Seq   OrderDate ProductID  Qty   Amt CustomerID
0          107    2  2016-01-02  p1036481    2  2100    c150417
1           69    1  2016-01-02  p1152861    1  1091    c212716
2           69    7  2016-01-02  p1013161    1  2600    c212716
3           69    8  2016-01-02  p1005771    1  1650    c212716
4           69   11  2016-01-02  p1089531    1  2600    c212716
...        ...  ...         ...       ...  ...   ...        ...
60649      105   19  2017-01-31  p1089531    1  2500    c217725
60650      105   24  2017-01-31  p1133371    2  2000    c217725
60651      105   26  2017-01-31  p1100371    5  1600    c217725
60652      107    1  2017-01-31  p1207281    1  3300    c234291
60653      107    2  2017-01-31  p1100371    1   400    c234291

[9177 rows x 7 columns]

### 5.4 추가 : Rolling & Shift
 - rolling은 주로 시계열 데이터에 대해서 이동평균값을 구하거나, 행을 shift(이동) 시킬 때 주로 사용합니다.
 - 시계열 데이터 : 행과 행에 시간순서가 있는 데이터(전제 : 시간순으로 정렬 되어 있는 상태)

In [90]:
import pandas as pd

In [91]:
stock = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/SK.csv') 
stock.head()

         Date      Open      High       Low     Close     AdjClose    Volume
0  2016-01-04  243000.0  245000.0  234500.0  234500.0  226585.6563  173905.0
1  2016-01-05  236000.0  244000.0  234000.0  241000.0  232866.2813  182985.0
2  2016-01-06  241000.0  243000.0  237500.0  239000.0  230933.7813  108574.0
3  2016-01-07  237000.0  243000.0  236000.0  240500.0  232383.1563  113376.0
4  2016-01-08  240500.0  242500.0  235000.0  241500.0  233349.4063   81557.0

* stock 데이터프레임에서 Date, Close, Volume 만을 남깁니다.

In [92]:
# stock.drop으로 칼럼을 삭제할수도 있고, 아래와 같이 특정 칼럼으로 구성된 데이터프레임을 만들수도 있습니다.
stock = stock[['Date', 'Close', 'Volume']]
#stock = stock.loc[:, ['Date', 'Close', 'Volume']]

stock.head()

         Date     Close    Volume
0  2016-01-04  234500.0  173905.0
1  2016-01-05  241000.0  182985.0
2  2016-01-06  239000.0  108574.0
3  2016-01-07  240500.0  113376.0
4  2016-01-08  241500.0   81557.0

기준일 포함하여 과거 3일의 평균을 데이터 프레임에 붙여봅시다.

In [93]:
#3칸의 윈도우가 계속 평균을 구하는것!
stock['Close_MA_3'] = stock['Close'].rolling(3).mean()
stock.head(10)

         Date     Close    Volume     Close_MA_3
0  2016-01-04  234500.0  173905.0            NaN
1  2016-01-05  241000.0  182985.0            NaN
2  2016-01-06  239000.0  108574.0  238166.666667
3  2016-01-07  240500.0  113376.0  240166.666667
4  2016-01-08  241500.0   81557.0  240333.333333
5  2016-01-11  239000.0   84152.0  240333.333333
6  2016-01-12  237500.0   86196.0  239333.333333
7  2016-01-13  242500.0   90207.0  239666.666667
8  2016-01-14  240000.0   96090.0  240000.000000
9  2016-01-15  234500.0   99523.0  239000.000000

In [94]:
stock['Close_MA_3_lag1'] = stock['Close_MA_3'].shift() # shift()안에 숫자를 변경해 보며 기능을 알아보자. default = 1
stock.head(10)

         Date     Close    Volume     Close_MA_3  Close_MA_3_lag1
0  2016-01-04  234500.0  173905.0            NaN              NaN
1  2016-01-05  241000.0  182985.0            NaN              NaN
2  2016-01-06  239000.0  108574.0  238166.666667              NaN
3  2016-01-07  240500.0  113376.0  240166.666667    238166.666667
4  2016-01-08  241500.0   81557.0  240333.333333    240166.666667
5  2016-01-11  239000.0   84152.0  240333.333333    240333.333333
6  2016-01-12  237500.0   86196.0  239333.333333    240333.333333
7  2016-01-13  242500.0   90207.0  239666.666667    239333.333333
8  2016-01-14  240000.0   96090.0  240000.000000    239666.666667
9  2016-01-15  234500.0   99523.0  239000.000000    240000.000000

In [95]:
# 이동평균(rolling)과 하루 뒤로 미루는(shift) 작업을 한꺼번에 하려면?
stock['Close_MA_3_lag1_2'] = stock['Close'].rolling(3).mean().shift()
stock.head(10)

,Date,Close,Volume,Close_MA_3,Close_MA_3_lag1,Close_MA_3_lag1_2
0,2016-01-04,234500.0,173905.0,NaN,NaN,NaN
1,2016-01-05,241000.0,182985.0,NaN,NaN,NaN
2,2016-01-06,239000.0,108574.0,238166.666667,NaN,NaN
3,2016-01-07,240500.0,113376.0,240166.666667,238166.666667,238166.666667
4,2016-01-08,241500.0,81557.0,240333.333333,240166.666667,240166.666667
5,2016-01-11,239000.0,84152.0,240333.333333,240333.333333,240333.333333
6,2016-01-12,237500.0,86196.0,239333.333333,240333.333333,240333.333333
7,2016-01-13,242500.0,90207.0,239666.666667,239333.333333,239333.333333
8,2016-01-14,240000.0,96090.0,240000.000000,239666.666667,239666.666667
9,2016-01-15,234500.0,99523.0,239000.000000,240000.000000,240000.000000

min_periods를 기억하자

In [96]:
stock['Close_MA_3(2)'] = stock['Close'].rolling(3, min_periods=1).mean()
stock.head()

,Date,Close,Volume,Close_MA_3,Close_MA_3_lag1,Close_MA_3_lag1_2,Close_MA_3(2)
0,2016-01-04,234500.0,173905.0,NaN,NaN,NaN,234500.000000
1,2016-01-05,241000.0,182985.0,NaN,NaN,NaN,237750.000000
2,2016-01-06,239000.0,108574.0,238166.666667,NaN,NaN,238166.666667
3,2016-01-07,240500.0,113376.0,240166.666667,238166.666667,238166.666667,240166.666667
4,2016-01-08,241500.0,81557.0,240333.333333,240166.666667,240166.666667,240333.333333

### 실습 8 : Rolling & Shift

* 아래 셀을 실행한 후 진행하시오

In [123]:
stock = pd.read_csv('https://raw.githubusercontent.com/DA4BAM/dataset/master/sknetworks.csv', sep=',', skipinitialspace=True) 
stock = stock[['Date', 'Close', 'Volume']]
stock.head()

         Date   Close  Volume
0  2015-01-02  8820.0  341169
1  2015-01-05  8820.0  484752
2  2015-01-06  8600.0  360161
3  2015-01-07  8650.0  300467
4  2015-01-08  8650.0  490843

* Q1. stock 데이터프레임에 전날 주가 컬럼과 전전날 주가 컬럼을 추가하세요.

In [124]:
stock['before']=stock['Close'].shift()

In [125]:
stock['bbefore']=stock['Close'].shift(2)

In [126]:
stock.head()

         Date   Close  Volume  before  bbefore
0  2015-01-02  8820.0  341169     NaN      NaN
1  2015-01-05  8820.0  484752  8820.0      NaN
2  2015-01-06  8600.0  360161  8820.0   8820.0
3  2015-01-07  8650.0  300467  8600.0   8820.0
4  2015-01-08  8650.0  490843  8650.0   8600.0

* Q2. 전전날 대비 전날 주가 증감 컬럼을 추가하세요.

In [129]:
stock['up']=(stock['before']-stock['bbefore'])

In [130]:
stock.head()

         Date   Close  Volume  before  bbefore     up
0  2015-01-02  8820.0  341169     NaN      NaN    NaN
1  2015-01-05  8820.0  484752  8820.0      NaN    NaN
2  2015-01-06  8600.0  360161  8820.0   8820.0    0.0
3  2015-01-07  8650.0  300467  8600.0   8820.0 -220.0
4  2015-01-08  8650.0  490843  8650.0   8600.0   50.0

* Q3. Q2에서 만든 컬럼의 각 데이터가 양수이면 1, 음수이면 0인 컬럼을 추가하세요.

In [131]:
stock.loc[(stock.up>0),'dist']=1

In [132]:
stock.loc[(stock.up<0),'dist']=0

In [133]:
stock.head()

         Date   Close  Volume  before  bbefore     up  dist
0  2015-01-02  8820.0  341169     NaN      NaN    NaN   NaN
1  2015-01-05  8820.0  484752  8820.0      NaN    NaN   NaN
2  2015-01-06  8600.0  360161  8820.0   8820.0    0.0   NaN
3  2015-01-07  8650.0  300467  8600.0   8820.0 -220.0   0.0
4  2015-01-08  8650.0  490843  8650.0   8600.0   50.0   1.0

* Q4. 3일 이동 최대 주가를 추가하세요.

In [134]:
#기준일 추가 -> Date
stock['3_max_c']=stock['Close'].rolling(3).max()

In [135]:
stock.head()

         Date   Close  Volume  before  bbefore     up  dist  3_max_c
0  2015-01-02  8820.0  341169     NaN      NaN    NaN   NaN      NaN
1  2015-01-05  8820.0  484752  8820.0      NaN    NaN   NaN      NaN
2  2015-01-06  8600.0  360161  8820.0   8820.0    0.0   NaN   8820.0
3  2015-01-07  8650.0  300467  8600.0   8820.0 -220.0   0.0   8820.0
4  2015-01-08  8650.0  490843  8650.0   8600.0   50.0   1.0   8650.0

* Q5. 기준일을 포함하지 않은, 과거 3일의 최대 주가를 추가하세요.

In [138]:
stock['Close_max_3_lag']=stock['Close'].rolling(3).max().shift(1)
stock.head(10)

,Date,Close,Volume,before,bbefore,up,dist,3_max_c,Close_max_3_lag
0,2015-01-02,8820.0,341169,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-05,8820.0,484752,8820.0,NaN,NaN,NaN,NaN,NaN
2,2015-01-06,8600.0,360161,8820.0,8820.0,0.0,NaN,8820.0,NaN
3,2015-01-07,8650.0,300467,8600.0,8820.0,-220.0,0.0,8820.0,8820.0
4,2015-01-08,8650.0,490843,8650.0,8600.0,50.0,1.0,8650.0,8820.0
5,2015-01-09,8700.0,506497,8650.0,8650.0,0.0,NaN,8700.0,8650.0
6,2015-01-12,8970.0,528617,8700.0,8650.0,50.0,1.0,8970.0,8700.0
7,2015-01-13,9070.0,1113489,8970.0,8700.0,270.0,1.0,9070.0,8970.0
8,2015-01-14,8780.0,791802,9070.0,8970.0,100.0,1.0,9070.0,9070.0
9,2015-01-15,8670.0,440961,8780.0,9070.0,-290.0,0.0,9070.0,9070.0

* Q6. 기준일을 포함하지 않은, 과거 7일 평균 거래량을 추가하세요.

In [139]:
stock['Volume_mean_7_lag']=stock['Volume'].rolling(7).mean().shift(1)
stock.head(10)

,Date,Close,Volume,before,bbefore,up,dist,3_max_c,Close_max_3_lag,Volume_mean_7_lag
0,2015-01-02,8820.0,341169,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-05,8820.0,484752,8820.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-01-06,8600.0,360161,8820.0,8820.0,0.0,NaN,8820.0,NaN,NaN
3,2015-01-07,8650.0,300467,8600.0,8820.0,-220.0,0.0,8820.0,8820.0,NaN
4,2015-01-08,8650.0,490843,8650.0,8600.0,50.0,1.0,8650.0,8820.0,NaN
5,2015-01-09,8700.0,506497,8650.0,8650.0,0.0,NaN,8700.0,8650.0,NaN
6,2015-01-12,8970.0,528617,8700.0,8650.0,50.0,1.0,8970.0,8700.0,NaN
7,2015-01-13,9070.0,1113489,8970.0,8700.0,270.0,1.0,9070.0,8970.0,430358.000000
8,2015-01-14,8780.0,791802,9070.0,8970.0,100.0,1.0,9070.0,9070.0,540689.428571
9,2015-01-15,8670.0,440961,8780.0,9070.0,-290.0,0.0,9070.0,9070.0,584553.714286

* Q7. 기준일을 포함하지 않은 과거 7일 평균 거래량을 추가하되, 최소 1일 데이터만 있어도 평균값이 나오게 만드시오.

In [140]:
stock['Volume_mean_7_lag_minper']=stock['Volume'].rolling(7,min_periods=1).mean().shift(1)
stock.head(10)

,Date,Close,Volume,before,bbefore,up,dist,3_max_c,Close_max_3_lag,Volume_mean_7_lag,Volume_mean_7_lag_minper
0,2015-01-02,8820.0,341169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-05,8820.0,484752,8820.0,NaN,NaN,NaN,NaN,NaN,NaN,341169.000000
2,2015-01-06,8600.0,360161,8820.0,8820.0,0.0,NaN,8820.0,NaN,NaN,412960.500000
3,2015-01-07,8650.0,300467,8600.0,8820.0,-220.0,0.0,8820.0,8820.0,NaN,395360.666667
4,2015-01-08,8650.0,490843,8650.0,8600.0,50.0,1.0,8650.0,8820.0,NaN,371637.250000
5,2015-01-09,8700.0,506497,8650.0,8650.0,0.0,NaN,8700.0,8650.0,NaN,395478.400000
6,2015-01-12,8970.0,528617,8700.0,8650.0,50.0,1.0,8970.0,8700.0,NaN,413981.500000
7,2015-01-13,9070.0,1113489,8970.0,8700.0,270.0,1.0,9070.0,8970.0,430358.000000,430358.000000
8,2015-01-14,8780.0,791802,9070.0,8970.0,100.0,1.0,9070.0,9070.0,540689.428571,540689.428571
9,2015-01-15,8670.0,440961,8780.0,9070.0,-290.0,0.0,9070.0,9070.0,584553.714286,584553.714286