In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('https://bit.ly/3HaMAtZ')

In [3]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,AgeGroup,Family,Age_scale1
0,0,3,male,22.0,1,0,7.2500,S,Age21_30,2,0.271174
1,1,1,female,38.0,1,0,71.2833,C,Age31_40,2,0.472229
2,1,3,female,26.0,0,0,7.9250,S,Age21_30,1,0.321438
3,1,1,female,35.0,1,0,53.1000,S,Age31_40,2,0.434531
4,0,3,male,35.0,0,0,8.0500,S,Age31_40,1,0.434531

In [11]:
data.groupby(['Pclass','Sex'])['Age'].mean()

Pclass  Sex
1       female    34.584787
        male      39.826393
2       female    28.540000
        male      30.876481
3       female    22.638958
        male      27.775216
Name: Age, dtype: float64

In [7]:
data=pd.read_csv('https://bit.ly/3HaMAtZ')

In [8]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,AgeGroup,Family,Age_scale1
0,0,3,male,22.0,1,0,7.2500,S,Age21_30,2,0.271174
1,1,1,female,38.0,1,0,71.2833,C,Age31_40,2,0.472229
2,1,3,female,26.0,0,0,7.9250,S,Age21_30,1,0.321438
3,1,1,female,35.0,1,0,53.1000,S,Age31_40,2,0.434531
4,0,3,male,35.0,0,0,8.0500,S,Age31_40,1,0.434531

In [13]:
data.groupby(['Embarked','Pclass'])[['Age']].median()

                   Age
Embarked Pclass
C        1       35.90
         2       27.00
         3       27.75
Q        1       38.50
         2       30.00
         3       27.00
S        1       35.90
         2       30.00
         3       26.00

In [14]:
a=[[11, 12, 13, 14],
   [15, 16, 17, 18], 
   [19, 20, 21, 22]]

In [19]:
a=np.array(a)

In [20]:
a[1:3,1:3]

array([[16, 17],
       [20, 21]])

In [21]:
a[1:,1:3]

array([[16, 17],
       [20, 21]])

In [22]:
a[-2:,-3:-1]

array([[16, 17],
       [20, 21]])

In [23]:
a[1:3,1:3]

array([[16, 17],
       [20, 21]])