# 성능튜닝

## 1.환경준비

### (1) import

In [2]:
#라이브러리들을 불러오자.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 전처리
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# 모델링
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import * 

import warnings    # 경고메시지 제외
warnings.filterwarnings(action='ignore')

### (2) 데이터 준비

* 변수설명
    * COLLEGE : 대학 졸업여부
    * INCOME : 연수입
    * OVERAGE : 월평균 초과사용 시간(분)
    * LEFTOVER : 월평균 잔여시간비율(%)
    * HOUSE : 집값
    * HANDSET_PRICE : 스마트폰 가격
    * OVER_15MINS_CALLS_PER_MONTH : 월평균 장기통화(15분이상) 횟수
    * AVERAGE_CALL_DURATION : 평균 통화 시간
    * REPORTED_SATISFACTION : 만족도 설문조사 결과
    * REPORTED_USAGE_LEVEL : 사용도 자가진단 결과
    * CONSIDERING_CHANGE_OF_PLAN : 향후 변경계획 설문조사 결과
    * CHURN : 이탈(번호이동) 여부 (1-이탈, 0-잔류, Target 변수)

In [3]:
# 데이터를 불러옵시다.
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/mobile_cust_churn.csv'
data = pd.read_csv(path)
data = data.sample(5000, random_state = 2022)
data['CHURN'] = data['CHURN'].map({'LEAVE':1, 'STAY':0})
data.head()

,id,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,REPORTED_SATISFACTION,REPORTED_USAGE_LEVEL,CONSIDERING_CHANGE_OF_PLAN,CHURN
3178,3179,0,119512,51,31,248566,229,5,2,very_sat,very_high,considering,1
14926,14927,1,142144,192,15,774317,581,29,4,unsat,very_little,never_thought,1
15116,15117,1,142308,0,79,306426,497,1,1,sat,little,considering,0
12733,12734,1,113385,0,0,333599,819,1,6,very_unsat,very_high,considering,1
14032,14033,1,90348,209,10,637286,360,26,4,unsat,little,actively_looking_into_it,0

## 2.데이터 준비

### (1) 데이터 정리

In [4]:
drop_cols = ['id']
data.drop(drop_cols, axis = 1, inplace = True )

### (2) 데이터분할1 : x, y 나누기

In [5]:
target = 'CHURN'
x = data.drop(target, axis = 1)
y = data.loc[:, target]

### (3) NA 조치

### (4) 가변수화

In [6]:
dumm_cols = ['REPORTED_SATISFACTION','REPORTED_USAGE_LEVEL','CONSIDERING_CHANGE_OF_PLAN']
x = pd.get_dummies(x, columns = dumm_cols, drop_first = True)

### (5) 데이터분할2 : train : validation 나누기

In [7]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = .3, random_state = 20)

### (6) Scaling

In [8]:
scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_val_s = scaler.transform(x_val)

## 3.선형모델 튜닝

Logistic Regression : 전진선택법
* 변수를 하나씩 늘려가면서
* AIC를 가장 낮추는 모델 찾기

### (1) 전진선택을 수행할 함수 만들기( **로지스틱 회귀** 용)

In [9]:
# 아래 함수는 로지스틱 회귀를 위한 전진선택법 함수 입니다.
import statsmodels.api as sm

def forward_stepwise_logistic(x_train, y_train):

    # 변수목록, 선택된 변수 목록, 단계별 모델과 AIC 저장소 정의
    features = list(x_train)
    selected = []
    step_df = pd.DataFrame({ 'step':[], 'feature':[],'aic':[]})

    # 
    for s in range(0, len(features)) :
        result =  { 'step':[], 'feature':[],'aic':[]}

        # 변수 목록에서 변수 한개씩 뽑아서 모델에 추가
        for f in features :
            vars = selected + [f]
            x_tr = x_train[vars]
            model = sm.Logit(y_train, x_tr).fit()
            result['step'].append(s+1)
            result['feature'].append(vars)
            result['aic'].append(model.aic)
        
        # 모델별 aic 집계
        temp = pd.DataFrame(result).sort_values('aic').reset_index(drop = True)

        # 만약 이전 aic보다 새로운 aic 가 크다면 멈추기
        if step_df['aic'].min() < temp['aic'].min() :
            break
        step_df = pd.concat([step_df, temp], axis = 0).reset_index(drop = True)

        # 선택된 변수 제거
        v = temp.loc[0,'feature'][s]
        features.remove(v)

        selected.append(v)
    
    # 선택된 변수와 step_df 결과 반환
    return selected, step_df

### (2) 전진선택법 수행

In [10]:
vars, result = forward_stepwise_logistic(x_train, y_train)

Optimization terminated successfully.
         Current function value: 0.693075
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693062
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.683528
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.693007
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.684909
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.693042
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.686899
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.692565
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692806
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.693137
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.691866
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.693146
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.693147
         Iterations 1
Optimization terminated successfully.
         Current function value: 0.693015
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692965
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692882
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692579
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693046
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693080
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693058
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.679039
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.679064
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682035
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.643056
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.679443
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.683317
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.674460
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682313
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682292
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.678103
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680840
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.683068
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.679251
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680933
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.681200
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.677933
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682371
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682062
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682863
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.642039
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635596
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.639711
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635522
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.642894
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.642569
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642966
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642830
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642966
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.641766
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642866
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642929
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642750
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642940
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.643014
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.643051
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642672
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.643053
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635399
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634914
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.633893
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635419
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635464
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635187
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635504
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634933
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635116
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635470
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635439
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635494
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635521
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635391
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635503
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635451
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635483
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633842
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633406
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633794
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633753
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633538
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633890
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633194
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633579
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633861
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633765
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633884
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633888
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633674
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633874
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633866
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633847
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633112
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632641
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633102
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632954
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632697
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633174
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633137
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633162
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633092
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633175
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633193
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633016
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633178
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633151
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633158
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632593
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632566
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632521
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632098
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632599
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632616
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632617
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632520
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632636
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632635
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632427
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632616
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632613
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632591
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632043
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632027
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631949
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632002
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632098
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632072
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631997
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632093
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632092
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631906
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632075
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632062
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632051
         Iterations 5

* 선택된 변수

In [11]:
vars

['OVERAGE',
 'HOUSE',
 'HANDSET_PRICE',
 'LEFTOVER',
 'REPORTED_SATISFACTION_very_sat',
 'INCOME',
 'REPORTED_SATISFACTION_sat']

In [13]:
list(x_train)

['COLLEGE',
 'INCOME',
 'OVERAGE',
 'LEFTOVER',
 'HOUSE',
 'HANDSET_PRICE',
 'OVER_15MINS_CALLS_PER_MONTH',
 'AVERAGE_CALL_DURATION',
 'REPORTED_SATISFACTION_sat',
 'REPORTED_SATISFACTION_unsat',
 'REPORTED_SATISFACTION_very_sat',
 'REPORTED_SATISFACTION_very_unsat',
 'REPORTED_USAGE_LEVEL_high',
 'REPORTED_USAGE_LEVEL_little',
 'REPORTED_USAGE_LEVEL_very_high',
 'REPORTED_USAGE_LEVEL_very_little',
 'CONSIDERING_CHANGE_OF_PLAN_considering',
 'CONSIDERING_CHANGE_OF_PLAN_never_thought',
 'CONSIDERING_CHANGE_OF_PLAN_no',
 'CONSIDERING_CHANGE_OF_PLAN_perhaps']

In [12]:
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)

In [14]:
result

,step,feature,aic
0,1.0,[OVERAGE],4786.699456
1,1.0,[HOUSE],4796.363859
2,1.0,[OVER_15MINS_CALLS_PER_MONTH],4810.294604
3,1.0,[REPORTED_SATISFACTION_very_sat],4845.064834
4,1.0,[AVERAGE_CALL_DURATION],4849.951663
...,...,...,...
114,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_SATISFACTION_very_unsat]",4442.309949
115,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, CONSIDERING_CHANGE_OF_PLAN_never_thought]",4442.315315
116,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_USAGE_LEVEL_high]",4442.316816
117,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_USAGE_LEVEL_very_little]",4442.448187
118,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_USAGE_LEVEL_very_high]",4442.451017

### (3) 모델링

* 전체 변수

In [15]:
m1 = LogisticRegression()
m1.fit(x_train, y_train)
p1 = m1.predict(x_val)

print(accuracy_score(y_val, p1))
print(classification_report(y_val, p1))

0.6333333333333333
              precision    recall  f1-score   support

           0       0.62      0.68      0.65       738
           1       0.65      0.59      0.62       762

    accuracy                           0.63      1500
   macro avg       0.63      0.63      0.63      1500
weighted avg       0.64      0.63      0.63      1500

* 전진선택법 변수

In [16]:
m2 = LogisticRegression()
m2.fit(x_train[vars], y_train)
p2 = m2.predict(x_val[vars])

print(accuracy_score(y_val, p2))
print(classification_report(y_val, p2))

0.634
              precision    recall  f1-score   support

           0       0.62      0.68      0.65       738
           1       0.66      0.59      0.62       762

    accuracy                           0.63      1500
   macro avg       0.64      0.63      0.63      1500
weighted avg       0.64      0.63      0.63      1500

## 4.하이퍼파라미터 튜닝

### (1) 필요한 함수 불러오기

In [17]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

### (2) Random Search

① 값의 범위를 지정한다.  
② 모델 선언(시도 횟수 지정)  
③ 모델링(값의 범위 내에서 시도 횟수만큼 랜덤하게 선택해서 시도한다.)  
④ 가장 성능이 좋은 값을 선정

#### ① 값의 범위를 지정한다.

In [18]:
# dictionary형태로 선언
params = { 'n_neighbors' : range(1,51), 'metric' : ['euclidean', 'manhattan']  }
params

{'n_neighbors': range(1, 51), 'metric': ['euclidean', 'manhattan']}

#### ② 모델 선언

In [19]:
# 기본모델
model = KNeighborsClassifier()

# Random Search 설정.
model_rs = RandomizedSearchCV(model
                            , params              # hyperparameter 범위 지정.
                            , cv=5                    # k-fold Cross Validation
                            , n_iter=5                # Random하게 시도할 횟수
                            )

#### ③ 모델링

In [20]:
# 학습 : model이 아니라 model_rs
model_rs.fit(x_train_s, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=5,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': range(1, 51)})

In [21]:
# 튜닝 결과
model_rs.cv_results_

{'mean_fit_time': array([0.0030158 , 0.00319996, 0.00294609, 0.00214896, 0.00243263]),
 'std_fit_time': array([0.00126895, 0.00157158, 0.00160856, 0.00093132, 0.00039965]),
 'mean_score_time': array([0.18397183, 0.22239218, 0.16474156, 0.15166988, 0.12704887]),
 'std_score_time': array([0.05150805, 0.07321146, 0.00956815, 0.0067256 , 0.0086143 ]),
 'param_n_neighbors': masked_array(data=[34, 30, 31, 21, 48],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_metric': masked_array(data=['euclidean', 'manhattan', 'manhattan', 'manhattan',
                    'euclidean'],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 34, 'metric': 'euclidean'},
  {'n_neighbors': 30, 'metric': 'manhattan'},
  {'n_neighbors': 31, 'metric': 'manhattan'},
  {'n_neighbors': 21, 'metric': 'manhattan'},
  {'n_neighbors': 48, 'metric': 'euclidean'}],
 'split0_test_score': array([0.61285714, 0.62142857, 0.63285714, 0.61571429, 0.60714286]),
 'split1_test_score': array([0.58857143, 0.61285714, 0.61571429, 0.62285714, 0.57571429]),
 'split2_test_score': array([0.60142857, 0.63428571, 0.63142857, 0.62      , 0.61571429]),
 'split3_test_score': array([0.57571429, 0.61      , 0.61285714, 0.60857143, 0.58714286]),
 'split4_test_score': array([0.58428571, 0.60428571, 0.59857143, 0.58571429, 0.58571429]),
 'mean_test_score': array([0.59257143, 0.61657143, 0.61828571, 0.61057143, 0.59428571]),
 'std_test_score': array([0.01310554, 0.01044324, 0.01272632, 0.01332789, 0.01479106]),
 'rank_test_score': array([5, 2, 1, 3, 4])}

In [22]:
model_rs.cv_results_['params']

[{'n_neighbors': 34, 'metric': 'euclidean'},
 {'n_neighbors': 30, 'metric': 'manhattan'},
 {'n_neighbors': 31, 'metric': 'manhattan'},
 {'n_neighbors': 21, 'metric': 'manhattan'},
 {'n_neighbors': 48, 'metric': 'euclidean'}]

In [23]:
model_rs.cv_results_['mean_test_score']

array([0.59257143, 0.61657143, 0.61828571, 0.61057143, 0.59428571])

In [24]:
# 최적의 파라미터
model_rs.best_params_

{'n_neighbors': 31, 'metric': 'manhattan'}

In [25]:
# 그때의 성능
model_rs.best_score_

0.6182857142857143

In [26]:
# best 모델로 예측 및 평가
pred = model_rs.predict(x_val_s) #5개의 모델이 있는데 지가 알아서 좋은 놈으로 시도함
print(classification_report(y_val, pred))

              precision    recall  f1-score   support

           0       0.58      0.72      0.65       738
           1       0.65      0.50      0.57       762

    accuracy                           0.61      1500
   macro avg       0.62      0.61      0.61      1500
weighted avg       0.62      0.61      0.60      1500

### (3) 실습 : Random Search

* decision tree로 튜닝을 시도해 봅시다.
    * max_depth : 1~10
    * min_samples_leaf : 10 ~ 100

#### ① 값의 범위를 지정한다.

In [62]:
param={'max_depth':[1,2,3,4,5,6,7,8,9,10],
      'min_samples_leaf':list(range(10,101))}

#### ② 모델 선언

In [63]:
model=DecisionTreeClassifier()

#### ③ 모델링

In [70]:
model_rs=RandomizedSearchCV(model,param,cv=3,scoring='accuracy',n_iter=20)

In [71]:
model_rs.fit(x_train_s,y_train)

RandomizedSearchCV(cv=3, estimator=DecisionTreeClassifier(), n_iter=20,
                   param_distributions={'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10],
                                        'min_samples_leaf': [10, 11, 12, 13, 14,
                                                             15, 16, 17, 18, 19,
                                                             20, 21, 22, 23, 24,
                                                             25, 26, 27, 28, 29,
                                                             30, 31, 32, 33, 34,
                                                             35, 36, 37, 38, 39, ...]},
                   scoring='accuracy')

In [72]:
model_rs.cv_results_

{'mean_fit_time': array([0.01090868, 0.01044424, 0.00799235, 0.00866874, 0.00855311,
        0.00950877, 0.01022482, 0.00936667, 0.01443005, 0.01258302,
        0.00872644, 0.00536664, 0.01030922, 0.01176747, 0.00931279,
        0.01497014, 0.00474485, 0.0083464 , 0.00630887, 0.0029796 ]),
 'std_fit_time': array([0.00103801, 0.00177525, 0.00138552, 0.00097667, 0.00080278,
        0.0003957 , 0.00023742, 0.00043618, 0.00411249, 0.00076474,
        0.00022044, 0.00089639, 0.00125401, 0.0020416 , 0.00028837,
        0.00289952, 0.00035143, 0.00099462, 0.00052077, 0.00070951]),
 'mean_score_time': array([0.00102417, 0.00166551, 0.00300248, 0.00099786, 0.00098562,
        0.00067552, 0.00098729, 0.00092912, 0.00099707, 0.00098451,
        0.00067528, 0.00110435, 0.00101328, 0.00167052, 0.00104737,
        0.00105341, 0.00108814, 0.0009853 , 0.00096464, 0.00107058]),
 'std_score_time': array([3.43462539e-05, 4.86112402e-04, 2.81840367e-03, 5.94720425e-07,
        1.40326838e-04, 4.77847671e-04, 1.45037425e-05, 7.30264341e-05,
        5.15042996e-07, 1.66327373e-04, 4.77733974e-04, 1.75425641e-04,
        2.25940655e-05, 9.52743878e-04, 7.18182299e-05, 1.88911518e-05,
        1.33697776e-04, 4.29296175e-05, 1.59629147e-04, 1.07842592e-04]),
 'param_min_samples_leaf': masked_array(data=[86, 66, 100, 97, 97, 65, 49, 92, 30, 19, 69, 35, 50,
                    50, 58, 21, 27, 95, 66, 66],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_depth': masked_array(data=[5, 7, 2, 5, 10, 8, 6, 10, 6, 8, 5, 2, 6, 10, 7, 10, 2,
                    10, 3, 1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'min_samples_leaf': 86, 'max_depth': 5},
  {'min_samples_leaf': 66, 'max_depth': 7},
  {'min_samples_leaf': 100, 'max_depth': 2},
  {'min_samples_leaf': 97, 'max_depth': 5},
  {'min_samples_leaf': 97, 'max_depth': 10},
  {'min_samples_leaf': 65, 'max_depth': 8},
  {'min_samples_leaf': 49, 'max_depth': 6},
  {'min_samples_leaf': 92, 'max_depth': 10},
  {'min_samples_leaf': 30, 'max_depth': 6},
  {'min_samples_leaf': 19, 'max_depth': 8},
  {'min_samples_leaf': 69, 'max_depth': 5},
  {'min_samples_leaf': 35, 'max_depth': 2},
  {'min_samples_leaf': 50, 'max_depth': 6},
  {'min_samples_leaf': 50, 'max_depth': 10},
  {'min_samples_leaf': 58, 'max_depth': 7},
  {'min_samples_leaf': 21, 'max_depth': 10},
  {'min_samples_leaf': 27, 'max_depth': 2},
  {'min_samples_leaf': 95, 'max_depth': 10},
  {'min_samples_leaf': 66, 'max_depth': 3},
  {'min_samples_leaf': 66, 'max_depth': 1}],
 'split0_test_score': array([0.71122536, 0.70179949, 0.65981148, 0.71208226, 0.71379606,
        0.69065981, 0.69065981, 0.71722365, 0.70608398, 0.69922879,
        0.70179949, 0.65981148, 0.69065981, 0.69065981, 0.69065981,
        0.70179949, 0.65981148, 0.71208226, 0.70351328, 0.63153385]),
 'split1_test_score': array([0.67609254, 0.67694944, 0.65724079, 0.67609254, 0.67609254,
        0.67780634, 0.68123393, 0.67609254, 0.68294773, 0.67609254,
        0.67952014, 0.65724079, 0.68123393, 0.68037704, 0.67866324,
        0.67866324, 0.65724079, 0.67609254, 0.67866324, 0.60582691]),
 'split2_test_score': array([0.68353345, 0.66723842, 0.66723842, 0.67838765, 0.67838765,
        0.66723842, 0.68439108, 0.67838765, 0.68181818, 0.67753002,
        0.68782161, 0.66723842, 0.67838765, 0.67324185, 0.68867925,
        0.66466552, 0.66723842, 0.67838765, 0.69554031, 0.60377358]),
 'mean_test_score': array([0.69028379, 0.68199578, 0.66143023, 0.68885415, 0.68942542,
        0.67856819, 0.68542828, 0.69056795, 0.6902833 , 0.68428378,
        0.68971375, 0.66143023, 0.68342713, 0.68142623, 0.68600077,
        0.68170942, 0.66143023, 0.68885415, 0.69257228, 0.61371145]),
 'std_test_score': array([0.01511631, 0.01455372, 0.00423898, 0.01645146, 0.0172581 ,
        0.00957691, 0.00391737, 0.0188717 , 0.01118228, 0.010584  ,
        0.00919338, 0.00423898, 0.00524462, 0.00714945, 0.00525104,
        0.01531213, 0.00423898, 0.01645146, 0.0103598 , 0.01263019]),
 'rank_test_score': array([ 3, 13, 17,  7,  6, 16, 10,  2,  4, 11,  5, 17, 12, 15,  9, 14, 17,
         7,  1, 20])}

In [73]:
model_rs.best_score_

0.6925722765806192

In [75]:
model_rs.best_params_

{'min_samples_leaf': 66, 'max_depth': 3}

In [76]:
pred=model_rs.predict(x_val)
print(classification_report(y_val,pred))

              precision    recall  f1-score   support

           0       0.62      0.42      0.50       738
           1       0.57      0.74      0.65       762

    accuracy                           0.59      1500
   macro avg       0.59      0.58      0.57      1500
weighted avg       0.59      0.59      0.58      1500

### (4) Grid Search

① 값의 범위를 지정한다.  
② 모델링(값의 범위 내에서 모든 조합을 다 시도한다.)  
③ 가장 성능이 좋은 값을 선정

#### ① 값의 범위를 지정한다.

In [77]:
# dictionary형태로 선언
params = { 'n_neighbors' : range(3,31,2), 'metric' : ['euclidean', 'manhattan']  }
params

{'n_neighbors': range(3, 31, 2), 'metric': ['euclidean', 'manhattan']}

#### ② 모델 선언

In [78]:
# 기본모델
model = KNeighborsClassifier()

# Random Search 설정.
model_gs = GridSearchCV(model, params, cv=5)

#### ③ 모델링

In [55]:
# 학습 : model이 아니라 model_rs
model_gs.fit(x_train_s, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': range(3, 31, 2)})

In [56]:
# 튜닝 결과
model_gs.cv_results_

{'mean_fit_time': array([0.00329647, 0.0038928 , 0.00224543, 0.00180812, 0.00346727,
        0.00220594, 0.00332184, 0.00442076, 0.00469232, 0.00727797,
        0.00239487, 0.00240469, 0.00302792, 0.00296774, 0.00362196,
        0.00441217, 0.00209842, 0.00201507, 0.00157294, 0.00279136,
        0.00191836, 0.00207   , 0.00215364, 0.00184994, 0.00243206,
        0.00156417, 0.00182199, 0.00225072]),
 'std_fit_time': array([0.00038514, 0.00306232, 0.00046873, 0.00040586, 0.00294521,
        0.0007355 , 0.00065191, 0.0029768 , 0.00380422, 0.0038213 ,
        0.00048749, 0.0005108 , 0.00079261, 0.00091532, 0.00159563,
        0.00375317, 0.00020714, 0.0010342 , 0.0004577 , 0.00131863,
        0.00079537, 0.000574  , 0.00044586, 0.0001639 , 0.00144591,
        0.00051091, 0.00014271, 0.00108568]),
 'mean_score_time': array([0.17381377, 0.1661942 , 0.11846085, 0.10237117, 0.12953548,
        0.14284678, 0.1526525 , 0.20091071, 0.19767013, 0.30191712,
        0.16304355, 0.15262856, 0.14990473, 0.1659512 , 0.13442674,
        0.17787228, 0.12472486, 0.12893505, 0.13550467, 0.17353144,
        0.16073456, 0.16113434, 0.15494652, 0.12411227, 0.12411842,
        0.1232265 , 0.13208399, 0.12321873]),
 'std_score_time': array([0.03217368, 0.01993652, 0.0176257 , 0.00797039, 0.02146081,
        0.02267734, 0.02414616, 0.03078939, 0.04485469, 0.06769294,
        0.01791385, 0.01932613, 0.00869705, 0.01218031, 0.01291077,
        0.03447308, 0.00738126, 0.00630166, 0.00864518, 0.0345098 ,
        0.01237557, 0.01399615, 0.02106707, 0.0032803 , 0.01258839,
        0.01004004, 0.0173812 , 0.0078799 ]),
 'param_metric': masked_array(data=['euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_n_neighbors': masked_array(data=[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 3,
                    5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'metric': 'euclidean', 'n_neighbors': 3},
  {'metric': 'euclidean', 'n_neighbors': 5},
  {'metric': 'euclidean', 'n_neighbors': 7},
  {'metric': 'euclidean', 'n_neighbors': 9},
  {'metric': 'euclidean', 'n_neighbors': 11},
  {'metric': 'euclidean', 'n_neighbors': 13},
  {'metric': 'euclidean', 'n_neighbors': 15},
  {'metric': 'euclidean', 'n_neighbors': 17},
  {'metric': 'euclidean', 'n_neighbors': 19},
  {'metric': 'euclidean', 'n_neighbors': 21},
  {'metric': 'euclidean', 'n_neighbors': 23},
  {'metric': 'euclidean', 'n_neighbors': 25},
  {'metric': 'euclidean', 'n_neighbors': 27},
  {'metric': 'euclidean', 'n_neighbors': 29},
  {'metric': 'manhattan', 'n_neighbors': 3},
  {'metric': 'manhattan', 'n_neighbors': 5},
  {'metric': 'manhattan', 'n_neighbors': 7},
  {'metric': 'manhattan', 'n_neighbors': 9},
  {'metric': 'manhattan', 'n_neighbors': 11},
  {'metric': 'manhattan', 'n_neighbors': 13},
  {'metric': 'manhattan', 'n_neighbors': 15},
  {'metric': 'manhattan', 'n_neighbors': 17},
  {'metric': 'manhattan', 'n_neighbors': 19},
  {'metric': 'manhattan', 'n_neighbors': 21},
  {'metric': 'manhattan', 'n_neighbors': 23},
  {'metric': 'manhattan', 'n_neighbors': 25},
  {'metric': 'manhattan', 'n_neighbors': 27},
  {'metric': 'manhattan', 'n_neighbors': 29}],
 'split0_test_score': array([0.58285714, 0.57857143, 0.58142857, 0.58285714, 0.57142857,
        0.57857143, 0.57428571, 0.59      , 0.59142857, 0.59      ,
        0.59857143, 0.58857143, 0.59142857, 0.58285714, 0.57714286,
        0.60428571, 0.58285714, 0.59571429, 0.60428571, 0.61285714,
        0.60571429, 0.60857143, 0.60571429, 0.61571429, 0.62714286,
        0.63285714, 0.63      , 0.62857143]),
 'split1_test_score': array([0.57714286, 0.59857143, 0.57857143, 0.57714286, 0.57857143,
        0.58714286, 0.59428571, 0.59285714, 0.6       , 0.59142857,
        0.60142857, 0.60571429, 0.58571429, 0.58571429, 0.58142857,
        0.59285714, 0.59714286, 0.59714286, 0.60428571, 0.58857143,
        0.59857143, 0.60428571, 0.61      , 0.62285714, 0.61428571,
        0.62      , 0.61571429, 0.62142857]),
 'split2_test_score': array([0.55428571, 0.56857143, 0.56857143, 0.55714286, 0.54428571,
        0.56285714, 0.57714286, 0.56714286, 0.56857143, 0.57857143,
        0.59      , 0.58142857, 0.58428571, 0.59142857, 0.54857143,
        0.57714286, 0.58      , 0.57428571, 0.59714286, 0.59      ,
        0.59428571, 0.60571429, 0.60714286, 0.62      , 0.61571429,
        0.61285714, 0.62857143, 0.63142857]),
 'split3_test_score': array([0.6       , 0.57857143, 0.58      , 0.57857143, 0.58142857,
        0.58285714, 0.59285714, 0.6       , 0.57857143, 0.57857143,
        0.57714286, 0.57571429, 0.56857143, 0.56857143, 0.59      ,
        0.58285714, 0.61      , 0.61142857, 0.60857143, 0.60571429,
        0.60571429, 0.59428571, 0.59428571, 0.60857143, 0.61285714,
        0.60714286, 0.61571429, 0.61428571]),
 'split4_test_score': array([0.58      , 0.57285714, 0.57714286, 0.57142857, 0.56428571,
        0.56142857, 0.56571429, 0.56285714, 0.55714286, 0.56428571,
        0.56285714, 0.57142857, 0.56857143, 0.57285714, 0.56857143,
        0.6       , 0.58857143, 0.57857143, 0.57714286, 0.59142857,
        0.59285714, 0.59428571, 0.59142857, 0.58571429, 0.58      ,
        0.58428571, 0.60285714, 0.59428571]),
 'mean_test_score': array([0.57885714, 0.57942857, 0.57714286, 0.57342857, 0.568     ,
        0.57457143, 0.58085714, 0.58257143, 0.57914286, 0.58057143,
        0.586     , 0.58457143, 0.57971429, 0.58028571, 0.57314286,
        0.59142857, 0.59171429, 0.59142857, 0.59828571, 0.59771429,
        0.59942857, 0.60142857, 0.60171429, 0.61057143, 0.61      ,
        0.61142857, 0.61857143, 0.618     ]),
 'std_test_score': array([0.01463571, 0.01028571, 0.00451754, 0.008926  , 0.0132665 ,
        0.01051335, 0.0110509 , 0.0147745 , 0.01537557, 0.00979796,
        0.01432566, 0.01203397, 0.0094069 , 0.00839825, 0.01409588,
        0.01018202, 0.01085714, 0.01349225, 0.01119037, 0.00975621,
        0.00546604, 0.00599319, 0.00741757, 0.01332789, 0.01583074,
        0.01606111, 0.00993859, 0.0132665 ]),
 'rank_test_score': array([23, 21, 24, 26, 28, 25, 17, 16, 22, 18, 14, 15, 20, 19, 27, 13, 11,
        12,  9, 10,  8,  7,  6,  4,  5,  3,  1,  2])}

In [57]:
model_gs.cv_results_['params']

[{'metric': 'euclidean', 'n_neighbors': 3},
 {'metric': 'euclidean', 'n_neighbors': 5},
 {'metric': 'euclidean', 'n_neighbors': 7},
 {'metric': 'euclidean', 'n_neighbors': 9},
 {'metric': 'euclidean', 'n_neighbors': 11},
 {'metric': 'euclidean', 'n_neighbors': 13},
 {'metric': 'euclidean', 'n_neighbors': 15},
 {'metric': 'euclidean', 'n_neighbors': 17},
 {'metric': 'euclidean', 'n_neighbors': 19},
 {'metric': 'euclidean', 'n_neighbors': 21},
 {'metric': 'euclidean', 'n_neighbors': 23},
 {'metric': 'euclidean', 'n_neighbors': 25},
 {'metric': 'euclidean', 'n_neighbors': 27},
 {'metric': 'euclidean', 'n_neighbors': 29},
 {'metric': 'manhattan', 'n_neighbors': 3},
 {'metric': 'manhattan', 'n_neighbors': 5},
 {'metric': 'manhattan', 'n_neighbors': 7},
 {'metric': 'manhattan', 'n_neighbors': 9},
 {'metric': 'manhattan', 'n_neighbors': 11},
 {'metric': 'manhattan', 'n_neighbors': 13},
 {'metric': 'manhattan', 'n_neighbors': 15},
 {'metric': 'manhattan', 'n_neighbors': 17},
 {'metric': 'manhattan', 'n_neighbors': 19},
 {'metric': 'manhattan', 'n_neighbors': 21},
 {'metric': 'manhattan', 'n_neighbors': 23},
 {'metric': 'manhattan', 'n_neighbors': 25},
 {'metric': 'manhattan', 'n_neighbors': 27},
 {'metric': 'manhattan', 'n_neighbors': 29}]

In [58]:
model_gs.cv_results_['mean_test_score']

array([0.57885714, 0.57942857, 0.57714286, 0.57342857, 0.568     ,
       0.57457143, 0.58085714, 0.58257143, 0.57914286, 0.58057143,
       0.586     , 0.58457143, 0.57971429, 0.58028571, 0.57314286,
       0.59142857, 0.59171429, 0.59142857, 0.59828571, 0.59771429,
       0.59942857, 0.60142857, 0.60171429, 0.61057143, 0.61      ,
       0.61142857, 0.61857143, 0.618     ])

In [59]:
# 최적의 파라미터
model_gs.best_params_

{'metric': 'manhattan', 'n_neighbors': 27}

In [60]:
# 그때의 성능
model_gs.best_score_

0.6185714285714285

In [61]:
# best 모델로 예측 및 평가
pred = model_gs.predict(x_val_s)
print(classification_report(y_val, pred))

              precision    recall  f1-score   support

           0       0.59      0.72      0.65       738
           1       0.65      0.51      0.57       762

    accuracy                           0.61      1500
   macro avg       0.62      0.61      0.61      1500
weighted avg       0.62      0.61      0.61      1500

### (5) 실습 : Grid Search

* decision tree로 튜닝을 시도해 봅시다.
    * max_depth : 1~10
    * min_samples_leaf : 10 ~ 100

#### ① 값의 범위를 지정한다.

#### ② 모델 선언

#### ③ 모델링