# 성능튜닝

## 1.환경준비

### (1) import

In [1]:
#라이브러리들을 불러오자.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 전처리
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# 모델링
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import * 

import warnings    # 경고메시지 제외
warnings.filterwarnings(action='ignore')

### (2) 데이터 준비

* 변수설명
    * COLLEGE : 대학 졸업여부
    * INCOME : 연수입
    * OVERAGE : 월평균 초과사용 시간(분)
    * LEFTOVER : 월평균 잔여시간비율(%)
    * HOUSE : 집값
    * HANDSET_PRICE : 스마트폰 가격
    * OVER_15MINS_CALLS_PER_MONTH : 월평균 장기통화(15분이상) 횟수
    * AVERAGE_CALL_DURATION : 평균 통화 시간
    * REPORTED_SATISFACTION : 만족도 설문조사 결과
    * REPORTED_USAGE_LEVEL : 사용도 자가진단 결과
    * CONSIDERING_CHANGE_OF_PLAN : 향후 변경계획 설문조사 결과
    * CHURN : 이탈(번호이동) 여부 (1-이탈, 0-잔류, Target 변수)

In [2]:
# 데이터를 불러옵시다.
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/mobile_cust_churn.csv'
data = pd.read_csv(path)
data = data.sample(5000, random_state = 2022)
data['CHURN'] = data['CHURN'].map({'LEAVE':1, 'STAY':0}) #sklearn에서는 y를 가변수화 할 필요가 없다. -> 반드시필요는 statsmodels, tensorflow(keras)
data.head()

,id,COLLEGE,INCOME,OVERAGE,LEFTOVER,HOUSE,HANDSET_PRICE,OVER_15MINS_CALLS_PER_MONTH,AVERAGE_CALL_DURATION,REPORTED_SATISFACTION,REPORTED_USAGE_LEVEL,CONSIDERING_CHANGE_OF_PLAN,CHURN
3178,3179,0,119512,51,31,248566,229,5,2,very_sat,very_high,considering,1
14926,14927,1,142144,192,15,774317,581,29,4,unsat,very_little,never_thought,1
15116,15117,1,142308,0,79,306426,497,1,1,sat,little,considering,0
12733,12734,1,113385,0,0,333599,819,1,6,very_unsat,very_high,considering,1
14032,14033,1,90348,209,10,637286,360,26,4,unsat,little,actively_looking_into_it,0

## 2.데이터 준비

### (1) 데이터 정리

In [3]:
drop_cols = ['id']
data.drop(drop_cols, axis = 1, inplace = True )

### (2) 데이터분할1 : x, y 나누기

In [4]:
target = 'CHURN'
x = data.drop(target, axis = 1)
y = data.loc[:, target]

### (3) NA 조치

### (4) 가변수화

In [5]:
dumm_cols = ['REPORTED_SATISFACTION','REPORTED_USAGE_LEVEL','CONSIDERING_CHANGE_OF_PLAN']
x = pd.get_dummies(x, columns = dumm_cols, drop_first = True)

### (5) 데이터분할2 : train : validation 나누기

In [6]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = .3, random_state = 20)

### (6) Scaling

In [7]:
scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_val_s = scaler.transform(x_val)

## 3.선형모델 튜닝

Logistic Regression : 전진선택법
* 변수를 하나씩 늘려가면서
* AIC를 가장 낮추는 모델 찾기

### (1) 전진선택을 수행할 함수 만들기( **로지스틱 회귀** 용)

In [8]:
# 아래 함수는 로지스틱 회귀를 위한 전진선택법 함수 입니다.
import statsmodels.api as sm

def forward_stepwise_logistic(x_train, y_train):

    # 변수목록, 선택된 변수 목록, 단계별 모델과 AIC 저장소 정의
    features = list(x_train)
    selected = []
    step_df = pd.DataFrame({ 'step':[], 'feature':[],'aic':[]})

    # 
    for s in range(0, len(features)) :
        result =  { 'step':[], 'feature':[],'aic':[]}

        # 변수 목록에서 변수 한개씩 뽑아서 모델에 추가
        for f in features :
            vars = selected + [f]
            x_tr = x_train[vars]
            model = sm.Logit(y_train, x_tr).fit()
            result['step'].append(s+1)
            result['feature'].append(vars)
            result['aic'].append(model.aic)
        
        # 모델별 aic 집계
        temp = pd.DataFrame(result).sort_values('aic').reset_index(drop = True)

        # 만약 이전 aic보다 새로운 aic 가 크다면 멈추기
        if step_df['aic'].min() < temp['aic'].min() :
            break
        step_df = pd.concat([step_df, temp], axis = 0).reset_index(drop = True)

        # 선택된 변수 제거
        v = temp.loc[0,'feature'][s]
        features.remove(v)

        selected.append(v)
    
    # 선택된 변수와 step_df 결과 반환
    return selected, step_df

### (2) 전진선택법 수행

In [9]:
vars, result = forward_stepwise_logistic(x_train, y_train)

Optimization terminated successfully.
         Current function value: 0.693075
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693062
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.683528
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.693007
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.684909
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.693042
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.686899
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.692565
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692806
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.693137
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.691866
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.693146
         Iterations 2
Optimization terminated successfully.
         Current function value: 0.693147
         Iterations 1
Optimization terminated successfully.
         Current function value: 0.693015
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692965
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692882
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.692579
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693046
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693080
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.693058
         Iterations 3
Optimization terminated successfully.
         Current function value: 0.679039
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.679064
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682035
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.643056
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.679443
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.683317
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.674460
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682313
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682292
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.678103
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680840
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.683068
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.679251
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.680933
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.681200
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.677933
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682371
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682062
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.682863
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.642039
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635596
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.639711
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635522
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.642894
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.642569
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642966
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642830
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642966
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.641766
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642866
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642929
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642750
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642940
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.643014
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.643051
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.642672
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.643053
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635399
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634914
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.633893
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635419
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635464
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635187
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635504
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.634933
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635116
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635470
         Iterations 4
Optimization terminated successfully.
         Current function value: 0.635439
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635494
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635521
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635391
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635503
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635451
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.635483
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633842
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633406
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633794
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633753
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633538
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633890
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633194
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633579
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633861
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633765
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633884
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633888
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633674
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633874
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633866
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633847
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633112
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632641
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633102
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632954
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632697
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633174
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633137
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633162
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633092
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633175
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633193
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633016
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633178
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633151
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.633158
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632593
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632566
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632521
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632098
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632599
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632616
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632617
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632520
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632636
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632635
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632427
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632616
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632613
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632591
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632043
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632027
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631949
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632002
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632098
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632072
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631997
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632093
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632092
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.631906
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632075
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632062
         Iterations 5
Optimization terminated successfully.
         Current function value: 0.632051
         Iterations 5

* 선택된 변수

In [10]:
vars

['OVERAGE',
 'HOUSE',
 'HANDSET_PRICE',
 'LEFTOVER',
 'REPORTED_SATISFACTION_very_sat',
 'INCOME',
 'REPORTED_SATISFACTION_sat']

In [11]:
list(x_train)

['COLLEGE',
 'INCOME',
 'OVERAGE',
 'LEFTOVER',
 'HOUSE',
 'HANDSET_PRICE',
 'OVER_15MINS_CALLS_PER_MONTH',
 'AVERAGE_CALL_DURATION',
 'REPORTED_SATISFACTION_sat',
 'REPORTED_SATISFACTION_unsat',
 'REPORTED_SATISFACTION_very_sat',
 'REPORTED_SATISFACTION_very_unsat',
 'REPORTED_USAGE_LEVEL_high',
 'REPORTED_USAGE_LEVEL_little',
 'REPORTED_USAGE_LEVEL_very_high',
 'REPORTED_USAGE_LEVEL_very_little',
 'CONSIDERING_CHANGE_OF_PLAN_considering',
 'CONSIDERING_CHANGE_OF_PLAN_never_thought',
 'CONSIDERING_CHANGE_OF_PLAN_no',
 'CONSIDERING_CHANGE_OF_PLAN_perhaps']

In [12]:
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)

In [13]:
result

,step,feature,aic
0,1.0,[OVERAGE],4786.699456
1,1.0,[HOUSE],4796.363859
2,1.0,[OVER_15MINS_CALLS_PER_MONTH],4810.294604
3,1.0,[REPORTED_SATISFACTION_very_sat],4845.064834
4,1.0,[AVERAGE_CALL_DURATION],4849.951663
...,...,...,...
114,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_SATISFACTION_very_unsat]",4442.309949
115,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, CONSIDERING_CHANGE_OF_PLAN_never_thought]",4442.315315
116,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_USAGE_LEVEL_high]",4442.316816
117,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_USAGE_LEVEL_very_little]",4442.448187
118,7.0,"[OVERAGE, HOUSE, HANDSET_PRICE, LEFTOVER, REPORTED_SATISFACTION_very_sat, INCOME, REPORTED_USAGE_LEVEL_very_high]",4442.451017

### (3) 모델링

* 전체 변수

In [14]:
m1 = LogisticRegression()
m1.fit(x_train, y_train)
p1 = m1.predict(x_val)

print(accuracy_score(y_val, p1))
print(classification_report(y_val, p1))

0.6333333333333333
              precision    recall  f1-score   support

           0       0.62      0.68      0.65       738
           1       0.65      0.59      0.62       762

    accuracy                           0.63      1500
   macro avg       0.63      0.63      0.63      1500
weighted avg       0.64      0.63      0.63      1500

* 전진선택법 변수

In [15]:
m2 = LogisticRegression()
m2.fit(x_train[vars], y_train)
p2 = m2.predict(x_val[vars])

print(accuracy_score(y_val, p2))
print(classification_report(y_val, p2))

0.634
              precision    recall  f1-score   support

           0       0.62      0.68      0.65       738
           1       0.66      0.59      0.62       762

    accuracy                           0.63      1500
   macro avg       0.64      0.63      0.63      1500
weighted avg       0.64      0.63      0.63      1500

## 4.하이퍼파라미터 튜닝

### (1) 필요한 함수 불러오기

In [16]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

### (2) Random Search

① 값의 범위를 지정한다.  
② 모델 선언(시도 횟수 지정)  
③ 모델링(값의 범위 내에서 시도 횟수만큼 랜덤하게 선택해서 시도한다.)  
④ 가장 성능이 좋은 값을 선정

#### ① 값의 범위를 지정한다.

In [17]:
# dictionary형태로 선언
params = { 'n_neighbors' : range(1,51), 'metric' : ['euclidean', 'manhattan']  }
params

{'n_neighbors': range(1, 51), 'metric': ['euclidean', 'manhattan']}

#### ② 모델 선언

In [18]:
# 기본모델
model = KNeighborsClassifier()

# Random Search 설정.
model_rs = RandomizedSearchCV(model
                            , params              # hyperparameter 범위 지정.
                            , cv=5                    # k-fold Cross Validation
                            , n_iter=5                # Random하게 시도할 횟수
                            )

#### ③ 모델링

In [19]:
# 학습 : model이 아니라 model_rs
model_rs.fit(x_train_s, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=5,
                   param_distributions={'metric': ['euclidean', 'manhattan'],
                                        'n_neighbors': range(1, 51)})

In [20]:
# 튜닝 결과
model_rs.cv_results_

{'mean_fit_time': array([0.00260248, 0.0027595 , 0.00299492, 0.00649281, 0.00806055]),
 'std_fit_time': array([0.00047937, 0.00121493, 0.00199276, 0.00460191, 0.00252892]),
 'mean_score_time': array([0.15715408, 0.17115321, 0.17972198, 0.48015079, 0.44441323]),
 'std_score_time': array([0.01745585, 0.02596661, 0.02550769, 0.178347  , 0.10051914]),
 'param_n_neighbors': masked_array(data=[41, 47, 33, 49, 36],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_metric': masked_array(data=['euclidean', 'manhattan', 'manhattan', 'manhattan',
                    'euclidean'],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 41, 'metric': 'euclidean'},
  {'n_neighbors': 47, 'metric': 'manhattan'},
  {'n_neighbors': 33, 'metric': 'manhattan'},
  {'n_neighbors': 49, 'metric': 'manhattan'},
  {'n_neighbors': 36, 'metric': 'euclidean'}],
 'split0_test_score': array([0.61      , 0.63285714, 0.63142857, 0.63857143, 0.61      ]),
 'split1_test_score': array([0.58      , 0.60714286, 0.62428571, 0.61857143, 0.57428571]),
 'split2_test_score': array([0.61857143, 0.63      , 0.62571429, 0.63428571, 0.61285714]),
 'split3_test_score': array([0.58428571, 0.60285714, 0.62      , 0.61285714, 0.59428571]),
 'split4_test_score': array([0.59      , 0.61      , 0.60571429, 0.60571429, 0.58142857]),
 'mean_test_score': array([0.59657143, 0.61657143, 0.62142857, 0.622     , 0.59457143]),
 'std_test_score': array([0.01505365, 0.01237509, 0.00866614, 0.01253892, 0.01521009]),
 'rank_test_score': array([4, 3, 2, 1, 5])}

In [21]:
model_rs.cv_results_['params']

[{'n_neighbors': 41, 'metric': 'euclidean'},
 {'n_neighbors': 47, 'metric': 'manhattan'},
 {'n_neighbors': 33, 'metric': 'manhattan'},
 {'n_neighbors': 49, 'metric': 'manhattan'},
 {'n_neighbors': 36, 'metric': 'euclidean'}]

In [22]:
model_rs.cv_results_['mean_test_score']

array([0.59657143, 0.61657143, 0.62142857, 0.622     , 0.59457143])

In [23]:
# 최적의 파라미터
model_rs.best_params_

{'n_neighbors': 49, 'metric': 'manhattan'}

In [24]:
# 그때의 성능
model_rs.best_score_

0.6220000000000001

In [25]:
# best 모델로 예측 및 평가
pred = model_rs.predict(x_val_s) #5개의 모델이 있는데 지가 알아서 좋은 놈으로 시도함
print(classification_report(y_val, pred))

              precision    recall  f1-score   support

           0       0.59      0.75      0.66       738
           1       0.67      0.49      0.57       762

    accuracy                           0.62      1500
   macro avg       0.63      0.62      0.62      1500
weighted avg       0.63      0.62      0.62      1500

### (3) 실습 : Random Search

* decision tree로 튜닝을 시도해 봅시다.
    * max_depth : 1~10
    * min_samples_leaf : 10 ~ 100

#### ① 값의 범위를 지정한다.

In [26]:
param={'max_depth':[1,2,3,4,5,6,7,8,9,10],
      'min_samples_leaf':list(range(10,101))}

#### ② 모델 선언

In [27]:
model=DecisionTreeClassifier()

#### ③ 모델링

In [28]:
model_rs=RandomizedSearchCV(model,param,cv=3,scoring='accuracy',n_iter=20)

In [29]:
model_rs.fit(x_train_s,y_train)

RandomizedSearchCV(cv=3, estimator=DecisionTreeClassifier(), n_iter=20,
                   param_distributions={'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10],
                                        'min_samples_leaf': [10, 11, 12, 13, 14,
                                                             15, 16, 17, 18, 19,
                                                             20, 21, 22, 23, 24,
                                                             25, 26, 27, 28, 29,
                                                             30, 31, 32, 33, 34,
                                                             35, 36, 37, 38, 39, ...]},
                   scoring='accuracy')

In [30]:
model_rs.cv_results_

{'mean_fit_time': array([0.02753107, 0.01965626, 0.01782513, 0.01659942, 0.01489814,
        0.00807722, 0.01374698, 0.02088873, 0.00732652, 0.01399477,
        0.02025342, 0.01294804, 0.01389742, 0.00802135, 0.01319345,
        0.01513664, 0.01109902, 0.02043732, 0.01238688, 0.01423446]),
 'std_fit_time': array([0.00621543, 0.00035428, 0.00412216, 0.00045495, 0.00052075,
        0.00078817, 0.00057099, 0.00176254, 0.00046141, 0.00160303,
        0.00381622, 0.00112378, 0.0007912 , 0.00084085, 0.00109816,
        0.00103876, 0.00125736, 0.0010367 , 0.00133522, 0.00307661]),
 'mean_score_time': array([0.00340438, 0.00197363, 0.00181055, 0.00135541, 0.00193055,
        0.00198698, 0.00199437, 0.0013303 , 0.00202998, 0.00166162,
        0.00261362, 0.00099746, 0.00117834, 0.00144474, 0.00248528,
        0.00166106, 0.00292126, 0.00151674, 0.00100358, 0.00228588]),
 'std_score_time': array([1.14614124e-03, 2.91696793e-05, 7.27106961e-04, 4.83337128e-04,
        1.44958278e-04, 7.64880121e-04, 8.13712330e-04, 4.69574065e-04,
        8.06208194e-05, 4.68560604e-04, 5.65629520e-04, 8.77806426e-07,
        2.56196810e-04, 6.33101860e-04, 1.51295619e-03, 9.40043390e-04,
        1.46919826e-03, 4.09919146e-04, 8.71524179e-06, 4.52835922e-04]),
 'param_min_samples_leaf': masked_array(data=[84, 87, 87, 56, 60, 18, 90, 18, 11, 93, 45, 100, 61,
                    70, 58, 11, 99, 15, 16, 85],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_depth': masked_array(data=[4, 9, 8, 6, 5, 2, 8, 8, 2, 9, 8, 10, 8, 2, 9, 6, 7, 8,
                    5, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'min_samples_leaf': 84, 'max_depth': 4},
  {'min_samples_leaf': 87, 'max_depth': 9},
  {'min_samples_leaf': 87, 'max_depth': 8},
  {'min_samples_leaf': 56, 'max_depth': 6},
  {'min_samples_leaf': 60, 'max_depth': 5},
  {'min_samples_leaf': 18, 'max_depth': 2},
  {'min_samples_leaf': 90, 'max_depth': 8},
  {'min_samples_leaf': 18, 'max_depth': 8},
  {'min_samples_leaf': 11, 'max_depth': 2},
  {'min_samples_leaf': 93, 'max_depth': 9},
  {'min_samples_leaf': 45, 'max_depth': 8},
  {'min_samples_leaf': 100, 'max_depth': 10},
  {'min_samples_leaf': 61, 'max_depth': 8},
  {'min_samples_leaf': 70, 'max_depth': 2},
  {'min_samples_leaf': 58, 'max_depth': 9},
  {'min_samples_leaf': 11, 'max_depth': 6},
  {'min_samples_leaf': 99, 'max_depth': 7},
  {'min_samples_leaf': 15, 'max_depth': 8},
  {'min_samples_leaf': 16, 'max_depth': 5},
  {'min_samples_leaf': 85, 'max_depth': 5}],
 'split0_test_score': array([0.70351328, 0.71722365, 0.71722365, 0.69065981, 0.70179949,
        0.65981148, 0.71722365, 0.6966581 , 0.65981148, 0.71808055,
        0.69065981, 0.71379606, 0.69065981, 0.65981148, 0.69065981,
        0.69837189, 0.71379606, 0.68723222, 0.70351328, 0.71122536]),
 'split1_test_score': array([0.67352185, 0.68037704, 0.68037704, 0.67866324, 0.68123393,
        0.65724079, 0.67609254, 0.67694944, 0.65724079, 0.67609254,
        0.68637532, 0.67609254, 0.67866324, 0.65724079, 0.67866324,
        0.65552699, 0.67609254, 0.67095116, 0.67523565, 0.67609254]),
 'split2_test_score': array([0.69296741, 0.67667238, 0.67667238, 0.68267581, 0.69725557,
        0.66723842, 0.67753002, 0.68096055, 0.66723842, 0.67838765,
        0.67667238, 0.68010292, 0.68096055, 0.66723842, 0.68867925,
        0.67581475, 0.68010292, 0.66638079, 0.69125214, 0.68353345]),
 'mean_test_score': array([0.69000085, 0.69142436, 0.69142436, 0.68399962, 0.69342966,
        0.66143023, 0.69028207, 0.68485603, 0.66143023, 0.69085358,
        0.68456917, 0.68999717, 0.68342787, 0.66143023, 0.68600077,
        0.67657121, 0.68999717, 0.67485472, 0.69000036, 0.69028379]),
 'std_test_score': array([0.01242234, 0.01830544, 0.01830544, 0.00498623, 0.00882095,
        0.00423898, 0.01905961, 0.00850446, 0.00423898, 0.01927516,
        0.00585142, 0.01690781, 0.00519905, 0.00423898, 0.00525104,
        0.01749953, 0.01690781, 0.00894889, 0.01157818, 0.01511631]),
 'rank_test_score': array([ 7,  2,  2, 14,  1, 18,  6, 12, 18,  4, 13,  9, 15, 18, 11, 16,  9,
        17,  8,  5])}

In [31]:
model_rs.best_score_

0.6934296645457337

In [32]:
model_rs.best_params_

{'min_samples_leaf': 60, 'max_depth': 5}

In [33]:
pred=model_rs.predict(x_val)
print(classification_report(y_val,pred))

              precision    recall  f1-score   support

           0       0.62      0.42      0.50       738
           1       0.57      0.74      0.65       762

    accuracy                           0.59      1500
   macro avg       0.59      0.58      0.57      1500
weighted avg       0.59      0.59      0.58      1500

### (4) Grid Search

① 값의 범위를 지정한다.  
② 모델링(값의 범위 내에서 모든 조합을 다 시도한다.)  
③ 가장 성능이 좋은 값을 선정

#### ① 값의 범위를 지정한다.

In [34]:
# dictionary형태로 선언
params = { 'n_neighbors' : range(3,31,2), 'metric' : ['euclidean', 'manhattan']  }
params

{'n_neighbors': range(3, 31, 2), 'metric': ['euclidean', 'manhattan']}

#### ② 모델 선언

In [35]:
# 기본모델
model = KNeighborsClassifier()

# Random Search 설정.
model_gs = GridSearchCV(model, params, cv=5)

#### ③ 모델링

In [36]:
# 학습 : model이 아니라 model_rs
model_gs.fit(x_train_s, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': range(3, 31, 2)})

In [37]:
# 튜닝 결과
model_gs.cv_results_

{'mean_fit_time': array([0.00335116, 0.00291142, 0.00244303, 0.00189137, 0.00262942,
        0.00212054, 0.00210772, 0.00178299, 0.00225954, 0.00259943,
        0.00309772, 0.00236588, 0.00188584, 0.00192313, 0.00157876,
        0.00145469, 0.00157514, 0.00172806, 0.0019351 , 0.00163698,
        0.00144429, 0.00158076, 0.00133867, 0.00176053, 0.00183773,
        0.00323682, 0.00175862, 0.00220523]),
 'std_fit_time': array([0.00186278, 0.00139047, 0.00045758, 0.0004861 , 0.0007796 ,
        0.00047269, 0.00067528, 0.00039326, 0.00036159, 0.00173766,
        0.00244186, 0.00044835, 0.00017738, 0.00062746, 0.00049802,
        0.00058582, 0.0005171 , 0.00038775, 0.00015333, 0.00044296,
        0.00053383, 0.00045266, 0.00053819, 0.00073925, 0.00037148,
        0.002563  , 0.00037753, 0.00039584]),
 'mean_score_time': array([0.14843316, 0.14869585, 0.10810452, 0.11704149, 0.11739554,
        0.10364079, 0.11810646, 0.10541415, 0.10274539, 0.10955248,
        0.10827031, 0.11307063, 0.10806265, 0.13048143, 0.10545888,
        0.09714479, 0.10406561, 0.10796928, 0.11682758, 0.09828916,
        0.09506283, 0.09944119, 0.095262  , 0.12831097, 0.10659928,
        0.16574364, 0.11957555, 0.10616355]),
 'std_score_time': array([0.03584644, 0.04120504, 0.00675409, 0.01799444, 0.01345445,
        0.00538848, 0.01474737, 0.00368144, 0.00632344, 0.01053845,
        0.00749609, 0.00737085, 0.00408247, 0.01251383, 0.01421838,
        0.00265634, 0.00733617, 0.00879189, 0.00438917, 0.00529841,
        0.00348949, 0.00488677, 0.00118066, 0.02594479, 0.00768291,
        0.06772148, 0.00809362, 0.00272802]),
 'param_metric': masked_array(data=['euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_n_neighbors': masked_array(data=[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 3,
                    5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'metric': 'euclidean', 'n_neighbors': 3},
  {'metric': 'euclidean', 'n_neighbors': 5},
  {'metric': 'euclidean', 'n_neighbors': 7},
  {'metric': 'euclidean', 'n_neighbors': 9},
  {'metric': 'euclidean', 'n_neighbors': 11},
  {'metric': 'euclidean', 'n_neighbors': 13},
  {'metric': 'euclidean', 'n_neighbors': 15},
  {'metric': 'euclidean', 'n_neighbors': 17},
  {'metric': 'euclidean', 'n_neighbors': 19},
  {'metric': 'euclidean', 'n_neighbors': 21},
  {'metric': 'euclidean', 'n_neighbors': 23},
  {'metric': 'euclidean', 'n_neighbors': 25},
  {'metric': 'euclidean', 'n_neighbors': 27},
  {'metric': 'euclidean', 'n_neighbors': 29},
  {'metric': 'manhattan', 'n_neighbors': 3},
  {'metric': 'manhattan', 'n_neighbors': 5},
  {'metric': 'manhattan', 'n_neighbors': 7},
  {'metric': 'manhattan', 'n_neighbors': 9},
  {'metric': 'manhattan', 'n_neighbors': 11},
  {'metric': 'manhattan', 'n_neighbors': 13},
  {'metric': 'manhattan', 'n_neighbors': 15},
  {'metric': 'manhattan', 'n_neighbors': 17},
  {'metric': 'manhattan', 'n_neighbors': 19},
  {'metric': 'manhattan', 'n_neighbors': 21},
  {'metric': 'manhattan', 'n_neighbors': 23},
  {'metric': 'manhattan', 'n_neighbors': 25},
  {'metric': 'manhattan', 'n_neighbors': 27},
  {'metric': 'manhattan', 'n_neighbors': 29}],
 'split0_test_score': array([0.58285714, 0.57857143, 0.58142857, 0.58285714, 0.57142857,
        0.57857143, 0.57428571, 0.59      , 0.59142857, 0.59      ,
        0.59857143, 0.58857143, 0.59142857, 0.58285714, 0.57714286,
        0.60428571, 0.58285714, 0.59571429, 0.60428571, 0.61285714,
        0.60571429, 0.60857143, 0.60571429, 0.61571429, 0.62714286,
        0.63285714, 0.63      , 0.62857143]),
 'split1_test_score': array([0.57714286, 0.59857143, 0.57857143, 0.57714286, 0.57857143,
        0.58714286, 0.59428571, 0.59285714, 0.6       , 0.59142857,
        0.60142857, 0.60571429, 0.58571429, 0.58571429, 0.58142857,
        0.59285714, 0.59714286, 0.59714286, 0.60428571, 0.58857143,
        0.59857143, 0.60428571, 0.61      , 0.62285714, 0.61428571,
        0.62      , 0.61571429, 0.62142857]),
 'split2_test_score': array([0.55428571, 0.56857143, 0.56857143, 0.55714286, 0.54428571,
        0.56285714, 0.57714286, 0.56714286, 0.56857143, 0.57857143,
        0.59      , 0.58142857, 0.58428571, 0.59142857, 0.54857143,
        0.57714286, 0.58      , 0.57428571, 0.59714286, 0.59      ,
        0.59428571, 0.60571429, 0.60714286, 0.62      , 0.61571429,
        0.61285714, 0.62857143, 0.63142857]),
 'split3_test_score': array([0.6       , 0.57857143, 0.58      , 0.57857143, 0.58142857,
        0.58285714, 0.59285714, 0.6       , 0.57857143, 0.57857143,
        0.57714286, 0.57571429, 0.56857143, 0.56857143, 0.59      ,
        0.58285714, 0.61      , 0.61142857, 0.60857143, 0.60571429,
        0.60571429, 0.59428571, 0.59428571, 0.60857143, 0.61285714,
        0.60714286, 0.61571429, 0.61428571]),
 'split4_test_score': array([0.58      , 0.57285714, 0.57714286, 0.57142857, 0.56428571,
        0.56142857, 0.56571429, 0.56285714, 0.55714286, 0.56428571,
        0.56285714, 0.57142857, 0.56857143, 0.57285714, 0.56857143,
        0.6       , 0.58857143, 0.57857143, 0.57714286, 0.59142857,
        0.59285714, 0.59428571, 0.59142857, 0.58571429, 0.58      ,
        0.58428571, 0.60285714, 0.59428571]),
 'mean_test_score': array([0.57885714, 0.57942857, 0.57714286, 0.57342857, 0.568     ,
        0.57457143, 0.58085714, 0.58257143, 0.57914286, 0.58057143,
        0.586     , 0.58457143, 0.57971429, 0.58028571, 0.57314286,
        0.59142857, 0.59171429, 0.59142857, 0.59828571, 0.59771429,
        0.59942857, 0.60142857, 0.60171429, 0.61057143, 0.61      ,
        0.61142857, 0.61857143, 0.618     ]),
 'std_test_score': array([0.01463571, 0.01028571, 0.00451754, 0.008926  , 0.0132665 ,
        0.01051335, 0.0110509 , 0.0147745 , 0.01537557, 0.00979796,
        0.01432566, 0.01203397, 0.0094069 , 0.00839825, 0.01409588,
        0.01018202, 0.01085714, 0.01349225, 0.01119037, 0.00975621,
        0.00546604, 0.00599319, 0.00741757, 0.01332789, 0.01583074,
        0.01606111, 0.00993859, 0.0132665 ]),
 'rank_test_score': array([23, 21, 24, 26, 28, 25, 17, 16, 22, 18, 14, 15, 20, 19, 27, 13, 11,
        12,  9, 10,  8,  7,  6,  4,  5,  3,  1,  2])}

In [38]:
model_gs.cv_results_['params']

[{'metric': 'euclidean', 'n_neighbors': 3},
 {'metric': 'euclidean', 'n_neighbors': 5},
 {'metric': 'euclidean', 'n_neighbors': 7},
 {'metric': 'euclidean', 'n_neighbors': 9},
 {'metric': 'euclidean', 'n_neighbors': 11},
 {'metric': 'euclidean', 'n_neighbors': 13},
 {'metric': 'euclidean', 'n_neighbors': 15},
 {'metric': 'euclidean', 'n_neighbors': 17},
 {'metric': 'euclidean', 'n_neighbors': 19},
 {'metric': 'euclidean', 'n_neighbors': 21},
 {'metric': 'euclidean', 'n_neighbors': 23},
 {'metric': 'euclidean', 'n_neighbors': 25},
 {'metric': 'euclidean', 'n_neighbors': 27},
 {'metric': 'euclidean', 'n_neighbors': 29},
 {'metric': 'manhattan', 'n_neighbors': 3},
 {'metric': 'manhattan', 'n_neighbors': 5},
 {'metric': 'manhattan', 'n_neighbors': 7},
 {'metric': 'manhattan', 'n_neighbors': 9},
 {'metric': 'manhattan', 'n_neighbors': 11},
 {'metric': 'manhattan', 'n_neighbors': 13},
 {'metric': 'manhattan', 'n_neighbors': 15},
 {'metric': 'manhattan', 'n_neighbors': 17},
 {'metric': 'manhattan', 'n_neighbors': 19},
 {'metric': 'manhattan', 'n_neighbors': 21},
 {'metric': 'manhattan', 'n_neighbors': 23},
 {'metric': 'manhattan', 'n_neighbors': 25},
 {'metric': 'manhattan', 'n_neighbors': 27},
 {'metric': 'manhattan', 'n_neighbors': 29}]

In [39]:
model_gs.cv_results_['mean_test_score']

array([0.57885714, 0.57942857, 0.57714286, 0.57342857, 0.568     ,
       0.57457143, 0.58085714, 0.58257143, 0.57914286, 0.58057143,
       0.586     , 0.58457143, 0.57971429, 0.58028571, 0.57314286,
       0.59142857, 0.59171429, 0.59142857, 0.59828571, 0.59771429,
       0.59942857, 0.60142857, 0.60171429, 0.61057143, 0.61      ,
       0.61142857, 0.61857143, 0.618     ])

In [40]:
# 최적의 파라미터
model_gs.best_params_

{'metric': 'manhattan', 'n_neighbors': 27}

In [41]:
# 그때의 성능
model_gs.best_score_

0.6185714285714285

In [42]:
# best 모델로 예측 및 평가
pred = model_gs.predict(x_val_s)
print(classification_report(y_val, pred))

              precision    recall  f1-score   support

           0       0.59      0.72      0.65       738
           1       0.65      0.51      0.57       762

    accuracy                           0.61      1500
   macro avg       0.62      0.61      0.61      1500
weighted avg       0.62      0.61      0.61      1500

### (5) 실습 : Grid Search

* decision tree로 튜닝을 시도해 봅시다.
    * max_depth : 1~10
    * min_samples_leaf : 10 ~ 100

#### ① 값의 범위를 지정한다.

In [54]:
parma={'max_depth':range(1,11),'min_samples_leaf':range(10,101,10)}

#### ② 모델 선언

In [55]:
model2=DecisionTreeClassifier()

#### ③ 모델링

In [63]:
model2_gs=GridSearchCV(model2,parma,cv=5,verbose=5)

In [64]:
model2_gs.fit(x_train_s,y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits
[CV 1/5] END ...............max_depth=1, min_samples_leaf=10; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=10; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=10; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=10; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=10; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=20; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=20; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=20; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=20; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=20; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=30; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=30; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=30; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=30; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=30; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=40; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=40; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=40; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=40; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=40; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=50; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=50; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=50; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=50; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=50; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=60; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=60; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=60; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=60; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=60; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=70; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=70; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=70; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=70; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=70; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=80; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=80; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=80; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=80; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=80; total time=   0.0s
[CV 1/5] END ...............max_depth=1, min_samples_leaf=90; total time=   0.0s
[CV 2/5] END ...............max_depth=1, min_samples_leaf=90; total time=   0.0s
[CV 3/5] END ...............max_depth=1, min_samples_leaf=90; total time=   0.0s
[CV 4/5] END ...............max_depth=1, min_samples_leaf=90; total time=   0.0s
[CV 5/5] END ...............max_depth=1, min_samples_leaf=90; total time=   0.0s
[CV 1/5] END ..............max_depth=1, min_samples_leaf=100; total time=   0.0s
[CV 2/5] END ..............max_depth=1, min_samples_leaf=100; total time=   0.0s
[CV 3/5] END ..............max_depth=1, min_samples_leaf=100; total time=   0.0s
[CV 4/5] END ..............max_depth=1, min_samples_leaf=100; total time=   0.0s
[CV 5/5] END ..............max_depth=1, min_samples_leaf=100; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=10; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=10; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=10; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=10; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=10; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=20; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=20; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=20; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=20; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=20; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=30; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=30; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=30; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=30; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=30; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=40; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=40; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=40; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=40; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=40; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=50; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=50; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=50; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=50; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=50; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=60; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=60; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=60; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=60; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=60; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=70; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=70; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=70; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=70; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=70; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=80; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=80; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=80; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=80; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=80; total time=   0.0s
[CV 1/5] END ...............max_depth=2, min_samples_leaf=90; total time=   0.0s
[CV 2/5] END ...............max_depth=2, min_samples_leaf=90; total time=   0.0s
[CV 3/5] END ...............max_depth=2, min_samples_leaf=90; total time=   0.0s
[CV 4/5] END ...............max_depth=2, min_samples_leaf=90; total time=   0.0s
[CV 5/5] END ...............max_depth=2, min_samples_leaf=90; total time=   0.0s
[CV 1/5] END ..............max_depth=2, min_samples_leaf=100; total time=   0.0s
[CV 2/5] END ..............max_depth=2, min_samples_leaf=100; total time=   0.0s
[CV 3/5] END ..............max_depth=2, min_samples_leaf=100; total time=   0.0s
[CV 4/5] END ..............max_depth=2, min_samples_leaf=100; total time=   0.0s
[CV 5/5] END ..............max_depth=2, min_samples_leaf=100; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=10; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=10; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=10; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=10; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=10; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=20; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=20; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=20; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=20; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=20; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=30; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=30; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=30; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=30; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=30; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=40; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=40; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=40; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=40; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=40; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=50; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=50; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=50; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=50; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=50; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=60; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=60; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=60; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=60; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=60; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=70; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=70; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=70; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=70; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=70; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=80; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=80; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=80; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=80; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=80; total time=   0.0s
[CV 1/5] END ...............max_depth=3, min_samples_leaf=90; total time=   0.0s
[CV 2/5] END ...............max_depth=3, min_samples_leaf=90; total time=   0.0s
[CV 3/5] END ...............max_depth=3, min_samples_leaf=90; total time=   0.0s
[CV 4/5] END ...............max_depth=3, min_samples_leaf=90; total time=   0.0s
[CV 5/5] END ...............max_depth=3, min_samples_leaf=90; total time=   0.0s
[CV 1/5] END ..............max_depth=3, min_samples_leaf=100; total time=   0.0s
[CV 2/5] END ..............max_depth=3, min_samples_leaf=100; total time=   0.0s
[CV 3/5] END ..............max_depth=3, min_samples_leaf=100; total time=   0.0s
[CV 4/5] END ..............max_depth=3, min_samples_leaf=100; total time=   0.0s
[CV 5/5] END ..............max_depth=3, min_samples_leaf=100; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=10; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=10; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=10; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=10; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=10; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=20; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=20; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=20; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=20; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=20; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=30; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=30; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=30; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=30; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=30; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=40; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=40; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=40; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=40; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=40; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=50; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=50; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=50; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=50; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=50; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=60; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=60; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=60; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=60; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=60; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=70; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=70; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=70; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=70; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=70; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=80; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=80; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=80; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=80; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=80; total time=   0.0s
[CV 1/5] END ...............max_depth=4, min_samples_leaf=90; total time=   0.0s
[CV 2/5] END ...............max_depth=4, min_samples_leaf=90; total time=   0.0s
[CV 3/5] END ...............max_depth=4, min_samples_leaf=90; total time=   0.0s
[CV 4/5] END ...............max_depth=4, min_samples_leaf=90; total time=   0.0s
[CV 5/5] END ...............max_depth=4, min_samples_leaf=90; total time=   0.0s
[CV 1/5] END ..............max_depth=4, min_samples_leaf=100; total time=   0.0s
[CV 2/5] END ..............max_depth=4, min_samples_leaf=100; total time=   0.0s
[CV 3/5] END ..............max_depth=4, min_samples_leaf=100; total time=   0.0s
[CV 4/5] END ..............max_depth=4, min_samples_leaf=100; total time=   0.0s
[CV 5/5] END ..............max_depth=4, min_samples_leaf=100; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=10; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=10; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=10; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=10; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=10; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=20; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=20; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=20; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=20; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=20; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=30; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=30; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=30; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=30; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=30; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=40; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=40; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=40; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=40; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=40; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=50; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=50; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=50; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=50; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=50; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=60; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=60; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=60; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=60; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=60; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=70; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=70; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=70; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=70; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=70; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=80; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=80; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=80; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=80; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=80; total time=   0.0s
[CV 1/5] END ...............max_depth=5, min_samples_leaf=90; total time=   0.0s
[CV 2/5] END ...............max_depth=5, min_samples_leaf=90; total time=   0.0s
[CV 3/5] END ...............max_depth=5, min_samples_leaf=90; total time=   0.0s
[CV 4/5] END ...............max_depth=5, min_samples_leaf=90; total time=   0.0s
[CV 5/5] END ...............max_depth=5, min_samples_leaf=90; total time=   0.0s
[CV 1/5] END ..............max_depth=5, min_samples_leaf=100; total time=   0.0s

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': range(1, 11),
                         'min_samples_leaf': range(10, 101, 10)},
             verbose=5)

In [65]:
model2_gs.cv_results_

{'mean_fit_time': array([0.01199098, 0.01395302, 0.01293631, 0.01042147, 0.01362305,
        0.00963907, 0.00870953, 0.00855322, 0.01003447, 0.00887928,
        0.01567307, 0.01169252, 0.0150485 , 0.01210566, 0.01205297,
        0.01523795, 0.0103076 , 0.01591311, 0.00968695, 0.00898824,
        0.01677232, 0.0142693 , 0.01364293, 0.0140914 , 0.01391082,
        0.01752815, 0.01403165, 0.01509247, 0.01584258, 0.01847339,
        0.01987033, 0.02903256, 0.01768217, 0.0233706 , 0.03914948,
        0.02700701, 0.0437428 , 0.04783149, 0.01891522, 0.02283387,
        0.02509518, 0.02340007, 0.02056694, 0.02574291, 0.02317371,
        0.0188221 , 0.02146764, 0.03147368, 0.02217069, 0.02147441,
        0.03522668, 0.02633219, 0.02423506, 0.02010698, 0.02138767,
        0.02071633, 0.02397537, 0.02623925, 0.01879382, 0.01801548,
        0.02182188, 0.02206264, 0.01738105, 0.0206604 , 0.01885324,
        0.01620836, 0.01476226, 0.01862936, 0.01504807, 0.01448421,
        0.02538743, 0.02109795, 0.01895852, 0.02212887, 0.01986747,
        0.015833  , 0.01517553, 0.0139678 , 0.01251044, 0.0178019 ,
        0.02962842, 0.03005362, 0.02277436, 0.02065287, 0.01708355,
        0.01465197, 0.01327777, 0.01506338, 0.01332598, 0.01568017,
        0.02266526, 0.02047992, 0.01973433, 0.01895347, 0.0187356 ,
        0.01838207, 0.01643004, 0.01583872, 0.01533341, 0.01268759]),
 'std_fit_time': array([4.24250045e-03, 1.59856805e-03, 6.04293181e-03, 2.80167577e-03,
        3.88911658e-03, 2.72370534e-03, 1.04702521e-03, 9.37365249e-04,
        1.06350685e-03, 2.22272900e-03, 2.20502912e-03, 3.55168727e-03,
        2.86556808e-03, 3.07203216e-03, 2.20071702e-03, 3.81713773e-03,
        2.16121803e-03, 3.42552716e-03, 1.78957412e-03, 6.55044101e-05,
        3.21213671e-03, 8.08780559e-04, 1.61209112e-03, 1.14489743e-03,
        1.15254474e-03, 2.55156659e-03, 1.51469852e-03, 9.63975792e-04,
        2.85208927e-03, 2.53763567e-03, 9.29927912e-04, 8.89031246e-03,
        2.83928619e-03, 7.46016953e-03, 4.85523390e-03, 3.28242890e-03,
        1.60177344e-02, 2.11290923e-02, 9.37209981e-04, 4.84710471e-03,
        3.95431801e-03, 4.48429036e-03, 1.86733289e-03, 3.56652508e-03,
        6.07750992e-03, 1.39083969e-03, 3.00985709e-03, 8.52847059e-03,
        2.65593341e-03, 5.29754620e-03, 6.35989018e-03, 2.51430985e-03,
        4.65690032e-03, 3.77626593e-04, 2.74246320e-03, 3.03481321e-03,
        4.93394301e-03, 1.36435591e-02, 3.95523355e-03, 1.66158549e-03,
        1.08442598e-03, 3.24804130e-03, 8.16295672e-04, 3.66869497e-03,
        1.36634210e-03, 9.29357853e-04, 1.14232828e-03, 4.05136040e-03,
        5.00104129e-04, 4.38998451e-04, 3.38888203e-03, 1.22930384e-03,
        1.45162222e-03, 1.68945563e-03, 1.88578595e-03, 6.33150056e-04,
        1.71705817e-03, 1.25315165e-03, 8.63909024e-04, 6.71094261e-03,
        1.56342590e-03, 3.91589617e-03, 1.03381620e-03, 2.62288627e-03,
        1.01080365e-03, 1.29835336e-03, 1.04442407e-03, 1.13870904e-03,
        4.46360471e-04, 1.42640558e-03, 2.88867326e-03, 3.24293028e-03,
        3.38032853e-03, 3.86766692e-03, 6.28877570e-03, 4.35731973e-03,
        3.88808747e-03, 4.33272262e-03, 5.26263504e-03, 2.34818874e-03]),
 'mean_score_time': array([0.00181813, 0.00401936, 0.00160279, 0.00238748, 0.00267196,
        0.00148516, 0.00244689, 0.00160046, 0.00373878, 0.00244122,
        0.00217447, 0.00151544, 0.00270786, 0.00243783, 0.00224171,
        0.00258942, 0.00207653, 0.00321918, 0.00138836, 0.00100617,
        0.00139604, 0.00105619, 0.00139227, 0.00179863, 0.00140944,
        0.00279851, 0.00160794, 0.00231471, 0.00181618, 0.00187507,
        0.00188217, 0.00353274, 0.00113068, 0.00248709, 0.0034595 ,
        0.00423055, 0.00520759, 0.00729446, 0.00162158, 0.00209661,
        0.00167475, 0.00138984, 0.00157619, 0.00148268, 0.00185828,
        0.00112634, 0.00270157, 0.00262799, 0.00221848, 0.00275149,
        0.0023747 , 0.00247517, 0.00133376, 0.00121326, 0.00259604,
        0.00168538, 0.00241456, 0.00121188, 0.00166254, 0.00241461,
        0.00176988, 0.00133319, 0.00098443, 0.00175471, 0.00140104,
        0.00152578, 0.00149908, 0.00120363, 0.00090642, 0.00131369,
        0.00220442, 0.00155396, 0.00088229, 0.00125494, 0.00168939,
        0.00153775, 0.00100293, 0.00096073, 0.00058665, 0.00139799,
        0.00141463, 0.00164552, 0.00154204, 0.0014699 , 0.00094657,
        0.00133119, 0.00092101, 0.00106592, 0.00102787, 0.00125699,
        0.00112815, 0.00108151, 0.00100875, 0.00080881, 0.00120101,
        0.00160451, 0.00127101, 0.00118847, 0.00112195, 0.0011096 ]),
 'std_score_time': array([7.50916450e-04, 1.10336373e-03, 1.18942545e-03, 1.46565385e-03,
        8.26007036e-04, 4.58101987e-04, 2.29202525e-03, 5.99301821e-04,
        1.37232595e-03, 1.02367341e-03, 9.61587957e-04, 4.87775266e-04,
        4.49895356e-04, 8.16104045e-04, 1.19930320e-03, 7.83681201e-04,
        6.28295749e-04, 1.28987761e-03, 8.24283797e-04, 7.50308079e-05,
        4.86891242e-04, 8.49491788e-05, 4.95088235e-04, 4.03326869e-04,
        4.86165699e-04, 7.12818849e-04, 4.88120719e-04, 6.36632942e-04,
        4.11659006e-04, 1.01907487e-03, 6.45291847e-04, 2.54174283e-03,
        5.07261861e-04, 9.68760666e-04, 9.95534932e-04, 3.37602252e-03,
        3.15959846e-03, 7.47237374e-03, 4.58469160e-04, 5.12249947e-04,
        8.35432576e-04, 6.62181267e-04, 4.42479499e-04, 4.51423286e-04,
        6.91135472e-04, 4.81854988e-04, 2.87350277e-03, 4.71847164e-04,
        9.44551837e-04, 2.02108280e-03, 9.77240517e-04, 2.36731634e-03,
        1.06694237e-03, 4.56539753e-04, 1.62001704e-03, 6.84492109e-04,
        1.82463206e-03, 3.46420669e-04, 1.18714541e-03, 1.76910033e-03,
        3.61355039e-04, 4.23003783e-04, 6.22487123e-05, 1.49181347e-03,
        5.41294877e-04, 4.75489228e-04, 3.91680863e-04, 3.83992987e-04,
        2.07178661e-04, 3.73825826e-04, 1.74858029e-03, 1.15789462e-03,
        4.70526024e-04, 1.57864977e-03, 1.23530572e-03, 5.34900813e-04,
        8.18522615e-06, 6.07127376e-05, 4.79461211e-04, 1.19840310e-03,
        7.90579724e-04, 5.68538753e-04, 7.00915384e-04, 4.68222948e-04,
        1.72481722e-04, 5.05223711e-04, 1.85853300e-04, 3.71507083e-04,
        4.68518654e-05, 3.88381930e-04, 2.56363878e-04, 1.34019357e-04,
        1.44561110e-05, 4.05922446e-04, 5.05381382e-04, 7.46314003e-04,
        7.40681965e-04, 4.03579416e-04, 5.36702461e-04, 2.69434810e-04]),
 'param_max_depth': masked_array(data=[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
                    2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
                    4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6,
                    6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8,
                    8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
                    10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 10, 20, 30,
                    40, 50, 60, 70, 80, 90, 100, 10, 20, 30, 40, 50, 60,
                    70, 80, 90, 100, 10, 20, 30, 40, 50, 60, 70, 80, 90,
                    100, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 10, 20,
                    30, 40, 50, 60, 70, 80, 90, 100, 10, 20, 30, 40, 50,
                    60, 70, 80, 90, 100, 10, 20, 30, 40, 50, 60, 70, 80,
                    90, 100, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 10,
                    20, 30, 40, 50, 60, 70, 80, 90, 100],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_leaf': 10},
  {'max_depth': 1, 'min_samples_leaf': 20},
  {'max_depth': 1, 'min_samples_leaf': 30},
  {'max_depth': 1, 'min_samples_leaf': 40},
  {'max_depth': 1, 'min_samples_leaf': 50},
  {'max_depth': 1, 'min_samples_leaf': 60},
  {'max_depth': 1, 'min_samples_leaf': 70},
  {'max_depth': 1, 'min_samples_leaf': 80},
  {'max_depth': 1, 'min_samples_leaf': 90},
  {'max_depth': 1, 'min_samples_leaf': 100},
  {'max_depth': 2, 'min_samples_leaf': 10},
  {'max_depth': 2, 'min_samples_leaf': 20},
  {'max_depth': 2, 'min_samples_leaf': 30},
  {'max_depth': 2, 'min_samples_leaf': 40},
  {'max_depth': 2, 'min_samples_leaf': 50},
  {'max_depth': 2, 'min_samples_leaf': 60},
  {'max_depth': 2, 'min_samples_leaf': 70},
  {'max_depth': 2, 'min_samples_leaf': 80},
  {'max_depth': 2, 'min_samples_leaf': 90},
  {'max_depth': 2, 'min_samples_leaf': 100},
  {'max_depth': 3, 'min_samples_leaf': 10},
  {'max_depth': 3, 'min_samples_leaf': 20},
  {'max_depth': 3, 'min_samples_leaf': 30},
  {'max_depth': 3, 'min_samples_leaf': 40},
  {'max_depth': 3, 'min_samples_leaf': 50},
  {'max_depth': 3, 'min_samples_leaf': 60},
  {'max_depth': 3, 'min_samples_leaf': 70},
  {'max_depth': 3, 'min_samples_leaf': 80},
  {'max_depth': 3, 'min_samples_leaf': 90},
  {'max_depth': 3, 'min_samples_leaf': 100},
  {'max_depth': 4, 'min_samples_leaf': 10},
  {'max_depth': 4, 'min_samples_leaf': 20},
  {'max_depth': 4, 'min_samples_leaf': 30},
  {'max_depth': 4, 'min_samples_leaf': 40},
  {'max_depth': 4, 'min_samples_leaf': 50},
  {'max_depth': 4, 'min_samples_leaf': 60},
  {'max_depth': 4, 'min_samples_leaf': 70},
  {'max_depth': 4, 'min_samples_leaf': 80},
  {'max_depth': 4, 'min_samples_leaf': 90},
  {'max_depth': 4, 'min_samples_leaf': 100},
  {'max_depth': 5, 'min_samples_leaf': 10},
  {'max_depth': 5, 'min_samples_leaf': 20},
  {'max_depth': 5, 'min_samples_leaf': 30},
  {'max_depth': 5, 'min_samples_leaf': 40},
  {'max_depth': 5, 'min_samples_leaf': 50},
  {'max_depth': 5, 'min_samples_leaf': 60},
  {'max_depth': 5, 'min_samples_leaf': 70},
  {'max_depth': 5, 'min_samples_leaf': 80},
  {'max_depth': 5, 'min_samples_leaf': 90},
  {'max_depth': 5, 'min_samples_leaf': 100},
  {'max_depth': 6, 'min_samples_leaf': 10},
  {'max_depth': 6, 'min_samples_leaf': 20},
  {'max_depth': 6, 'min_samples_leaf': 30},
  {'max_depth': 6, 'min_samples_leaf': 40},
  {'max_depth': 6, 'min_samples_leaf': 50},
  {'max_depth': 6, 'min_samples_leaf': 60},
  {'max_depth': 6, 'min_samples_leaf': 70},
  {'max_depth': 6, 'min_samples_leaf': 80},
  {'max_depth': 6, 'min_samples_leaf': 90},
  {'max_depth': 6, 'min_samples_leaf': 100},
  {'max_depth': 7, 'min_samples_leaf': 10},
  {'max_depth': 7, 'min_samples_leaf': 20},
  {'max_depth': 7, 'min_samples_leaf': 30},
  {'max_depth': 7, 'min_samples_leaf': 40},
  {'max_depth': 7, 'min_samples_leaf': 50},
  {'max_depth': 7, 'min_samples_leaf': 60},
  {'max_depth': 7, 'min_samples_leaf': 70},
  {'max_depth': 7, 'min_samples_leaf': 80},
  {'max_depth': 7, 'min_samples_leaf': 90},
  {'max_depth': 7, 'min_samples_leaf': 100},
  {'max_depth': 8, 'min_samples_leaf': 10},
  {'max_depth': 8, 'min_samples_leaf': 20},
  {'max_depth': 8, 'min_samples_leaf': 30},
  {'max_depth': 8, 'min_samples_leaf': 40},
  {'max_depth': 8, 'min_samples_leaf': 50},
  {'max_depth': 8, 'min_samples_leaf': 60},
  {'max_depth': 8, 'min_samples_leaf': 70},
  {'max_depth': 8, 'min_samples_leaf': 80},
  {'max_depth': 8, 'min_samples_leaf': 90},
  {'max_depth': 8, 'min_samples_leaf': 100},
  {'max_depth': 9, 'min_samples_leaf': 10},
  {'max_depth': 9, 'min_samples_leaf': 20},
  {'max_depth': 9, 'min_samples_leaf': 30},
  {'max_depth': 9, 'min_samples_leaf': 40},
  {'max_depth': 9, 'min_samples_leaf': 50},
  {'max_depth': 9, 'min_samples_leaf': 60},
  {'max_depth': 9, 'min_samples_leaf': 70},
  {'max_depth': 9, 'min_samples_leaf': 80},
  {'max_depth': 9, 'min_samples_leaf': 90},
  {'max_depth': 9, 'min_samples_leaf': 100},
  {'max_depth': 10, 'min_samples_leaf': 10},
  {'max_depth': 10, 'min_samples_leaf': 20},
  {'max_depth': 10, 'min_samples_leaf': 30},
  {'max_depth': 10, 'min_samples_leaf': 40},
  {'max_depth': 10, 'min_samples_leaf': 50},
  {'max_depth': 10, 'min_samples_leaf': 60},
  {'max_depth': 10, 'min_samples_leaf': 70},
  {'max_depth': 10, 'min_samples_leaf': 80},
  {'max_depth': 10, 'min_samples_leaf': 90},
  {'max_depth': 10, 'min_samples_leaf': 100}],
 'split0_test_score': array([0.64285714, 0.64285714, 0.64285714, 0.64285714, 0.64285714,
        0.64285714, 0.64285714, 0.64285714, 0.64285714, 0.64285714,
        0.66571429, 0.66571429, 0.66571429, 0.66571429, 0.66571429,
        0.66571429, 0.66571429, 0.66571429, 0.66571429, 0.66571429,
        0.70285714, 0.70285714, 0.70285714, 0.70285714, 0.70285714,
        0.70285714, 0.70285714, 0.70285714, 0.70285714, 0.70285714,
        0.70571429, 0.7       , 0.70285714, 0.70285714, 0.70285714,
        0.70285714, 0.70285714, 0.70285714, 0.70285714, 0.70285714,
        0.70428571, 0.71857143, 0.72714286, 0.72142857, 0.72142857,
        0.72142857, 0.72142857, 0.72142857, 0.72142857, 0.72142857,
        0.72142857, 0.72      , 0.72857143, 0.70857143, 0.70857143,
        0.70857143, 0.70857143, 0.72142857, 0.72142857, 0.72142857,
        0.71142857, 0.71571429, 0.73428571, 0.71428571, 0.70857143,
        0.70857143, 0.71571429, 0.72857143, 0.72142857, 0.72142857,
        0.70285714, 0.72285714, 0.73142857, 0.71285714, 0.70714286,
        0.70857143, 0.71571429, 0.72857143, 0.72142857, 0.72142857,
        0.68285714, 0.71142857, 0.73428571, 0.71285714, 0.70714286,
        0.70857143, 0.71571429, 0.72857143, 0.72142857, 0.72142857,
        0.67714286, 0.71428571, 0.73428571, 0.71285714, 0.70714286,
        0.70857143, 0.71571429, 0.72857143, 0.72142857, 0.72142857]),
 'split1_test_score': array([0.61571429, 0.61571429, 0.61571429, 0.61571429, 0.61571429,
        0.61571429, 0.61571429, 0.61571429, 0.61571429, 0.61571429,
        0.65857143, 0.65857143, 0.65857143, 0.65857143, 0.65857143,
        0.65857143, 0.65857143, 0.65857143, 0.65857143, 0.65857143,
        0.69285714, 0.69714286, 0.69714286, 0.69714286, 0.69714286,
        0.69714286, 0.69714286, 0.69714286, 0.69714286, 0.69714286,
        0.69      , 0.69285714, 0.69285714, 0.69285714, 0.69142857,
        0.69142857, 0.69142857, 0.69142857, 0.70285714, 0.69428571,
        0.68571429, 0.68      , 0.68571429, 0.69142857, 0.68285714,
        0.68      , 0.68      , 0.68      , 0.69142857, 0.68285714,
        0.67428571, 0.68142857, 0.69142857, 0.69142857, 0.67571429,
        0.67571429, 0.67571429, 0.67571429, 0.68428571, 0.67857143,
        0.68      , 0.67857143, 0.70571429, 0.70428571, 0.68      ,
        0.67571429, 0.67571429, 0.67571429, 0.68428571, 0.67857143,
        0.66142857, 0.67428571, 0.69142857, 0.69571429, 0.68      ,
        0.67571429, 0.67571429, 0.67571429, 0.68428571, 0.67857143,
        0.66428571, 0.67142857, 0.69142857, 0.69571429, 0.68      ,
        0.67571429, 0.67571429, 0.67571429, 0.68428571, 0.67857143,
        0.66285714, 0.67857143, 0.69      , 0.69571429, 0.68      ,
        0.67571429, 0.67571429, 0.67571429, 0.68428571, 0.67857143]),
 'split2_test_score': array([0.60142857, 0.60142857, 0.60142857, 0.60142857, 0.60142857,
        0.60142857, 0.60142857, 0.60142857, 0.60142857, 0.60142857,
        0.65428571, 0.65428571, 0.65428571, 0.65428571, 0.65428571,
        0.65428571, 0.65428571, 0.65428571, 0.65428571, 0.65428571,
        0.68      , 0.68      , 0.68      , 0.68      , 0.68      ,
        0.68      , 0.68      , 0.68      , 0.68      , 0.69      ,
        0.67428571, 0.67285714, 0.67142857, 0.67142857, 0.67142857,
        0.67142857, 0.67571429, 0.67142857, 0.68      , 0.67714286,
        0.66714286, 0.67571429, 0.67857143, 0.67285714, 0.67285714,
        0.68      , 0.67285714, 0.66857143, 0.67714286, 0.67428571,
        0.67285714, 0.67428571, 0.67571429, 0.67285714, 0.67857143,
        0.68428571, 0.67857143, 0.67428571, 0.69      , 0.68142857,
        0.65714286, 0.67571429, 0.67714286, 0.67714286, 0.68142857,
        0.68714286, 0.67857143, 0.67428571, 0.69      , 0.68142857,
        0.65428571, 0.67571429, 0.67285714, 0.68428571, 0.69285714,
        0.68714286, 0.67857143, 0.67428571, 0.69      , 0.68142857,
        0.65571429, 0.68428571, 0.68142857, 0.67714286, 0.68142857,
        0.68714286, 0.67857143, 0.67428571, 0.69      , 0.68142857,
        0.65571429, 0.67428571, 0.67285714, 0.67714286, 0.68142857,
        0.68714286, 0.67857143, 0.67428571, 0.69      , 0.68142857]),
 'split3_test_score': array([0.59714286, 0.59714286, 0.59714286, 0.59714286, 0.59714286,
        0.59714286, 0.59714286, 0.59714286, 0.59714286, 0.59714286,
        0.67285714, 0.67285714, 0.67285714, 0.67285714, 0.67285714,
        0.67285714, 0.67285714, 0.67285714, 0.67285714, 0.67285714,
        0.69428571, 0.69428571, 0.69428571, 0.69428571, 0.69428571,
        0.69428571, 0.69428571, 0.69428571, 0.69428571, 0.69428571,
        0.68857143, 0.68714286, 0.69      , 0.68857143, 0.68857143,
        0.68714286, 0.70142857, 0.70857143, 0.70857143, 0.70142857,
        0.68142857, 0.69285714, 0.69571429, 0.69428571, 0.68571429,
        0.67857143, 0.69857143, 0.70428571, 0.70428571, 0.69714286,
        0.65285714, 0.65857143, 0.67      , 0.67571429, 0.69285714,
        0.68571429, 0.70571429, 0.70428571, 0.70428571, 0.69714286,
        0.66857143, 0.69571429, 0.71      , 0.69857143, 0.68571429,
        0.67571429, 0.69571429, 0.7       , 0.70285714, 0.69714286,
        0.66285714, 0.69142857, 0.7       , 0.69142857, 0.68571429,
        0.67571429, 0.69571429, 0.7       , 0.70285714, 0.69714286,
        0.66857143, 0.69142857, 0.71142857, 0.68714286, 0.68571429,
        0.67571429, 0.69571429, 0.7       , 0.70285714, 0.69714286,
        0.66428571, 0.69285714, 0.71428571, 0.68142857, 0.68571429,
        0.67571429, 0.69571429, 0.7       , 0.70285714, 0.69714286]),
 'split4_test_score': array([0.61285714, 0.61285714, 0.61285714, 0.61285714, 0.61285714,
        0.61285714, 0.61285714, 0.61285714, 0.61285714, 0.61285714,
        0.65571429, 0.65571429, 0.65571429, 0.65571429, 0.65571429,
        0.65571429, 0.65571429, 0.65571429, 0.65571429, 0.65571429,
        0.69      , 0.69142857, 0.69142857, 0.69142857, 0.69142857,
        0.69142857, 0.69142857, 0.69142857, 0.69142857, 0.69142857,
        0.68857143, 0.69      , 0.69      , 0.69285714, 0.69285714,
        0.69285714, 0.69285714, 0.69285714, 0.69285714, 0.69      ,

In [66]:
model2_gs.best_params_

{'max_depth': 7, 'min_samples_leaf': 30}

In [67]:
model2_gs.best_score_ #하이퍼 파라미터 값을 조정 -> 모델 -> 검증
#튜닝해서 가장 좋은 결과

0.7005714285714285

In [68]:
pred=model2_gs.predict(x_val)

In [70]:
print(confusion_matrix(y_val,pred))
print('-'*50)
print(classification_report(y_val,pred))

[[313 425]
 [195 567]]
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.62      0.42      0.50       738
           1       0.57      0.74      0.65       762

    accuracy                           0.59      1500
   macro avg       0.59      0.58      0.57      1500
weighted avg       0.59      0.59      0.58      1500