### webcrawling
- 웹 크롤링의 종류
    - 정적페이지 : 페이지의 데이터가 변경될때 url이 변경 , html 포맷
    - 동적페이지 : 페이지의 데이터가 변경될때 url이 변경되지 않음 , json 포맷
- request package
    - 브라우저의 URL을 입력하면 서버에서 데이터를 다운받아 화면에 출력 : URL -> Data
    - request package : URL -> Data  즉 브라우저 기능을 파이썬으로 구현

### Naver Stock Data
- Kospi 지수
- Kosdaq 지수
- USD : 원달러 환율

In [1]:
import requests
import pandas as pd

 1. 웹서비스를 분석 : 크롬 개발자 도구 -> URL 최종 획득가능
 2. Requests(데이터요청) -> response (데이터 얻어오기) -> JSON(str)
 3. JSON(str) ->list, dict -> Dataframe

In [3]:
# 1. 웹서비스를 분석 : 크롬 개발자 도구 -> URL 최종 획득가능
# 크롬개발자 도구 -> clear -> 더보기 버튼 -> head의 url, post등 확인
url = "https://m.stock.naver.com/api/index/KOSPI/price?pageSize=10&page=4"

In [5]:
# 2. requests(데이터요청) -> response (데이터 얻어오기) -> JSON(str)
response=requests.get(url)
response

In [7]:
response.text[:200]

'[{"localTradedAt":"2022-06-22","closePrice":"2,342.81","compareToPreviousClosePrice":"-66.12","compareToPreviousPrice":{"code":"5","text":"하락","name":"FALLING"},"fluctuationsRatio":"-2.74","openPrice"'

In [9]:
# 3. JSON(str) ->list, dict -> Dataframe
data=response.json()
type(data),data[:1]

(list,
 [{'localTradedAt': '2022-06-22',
   'closePrice': '2,342.81',
   'compareToPreviousClosePrice': '-66.12',
   'compareToPreviousPrice': {'code': '5', 'text': '하락', 'name': 'FALLING'},
   'fluctuationsRatio': '-2.74',
   'openPrice': '2,417.11',
   'highPrice': '2,418.05',
   'lowPrice': '2,342.81'}])

In [14]:
#데이터프레임
df=pd.DataFrame(data)[["localTradedAt","closePrice"]]
df

  localTradedAt closePrice
0    2022-06-22   2,342.81
1    2022-06-21   2,408.93
2    2022-06-20   2,391.03
3    2022-06-17   2,440.93
4    2022-06-16   2,451.41
5    2022-06-15   2,447.38
6    2022-06-14   2,492.97
7    2022-06-13   2,504.51
8    2022-06-10   2,595.87
9    2022-06-09   2,625.44

#### 함수 만들기

In [37]:
#4. 함수 만들기 : params = pagesize,page
def stock_price(pagesize,page,code="KOSPI"):
    """This function is crawling stock price from webpage.
    Param
    ------
    pagesize : int , one page size
    page : int, page number
    code : string, kospi or kosdaq
    
    Return
    ------
    type : Dataframe, display date, price columns
    """
    url=f"https://m.stock.naver.com/api/index/{code}/price?pageSize={pagesize}&page={page}"
    response=requests.get(url)
    data=response.json()
    return pd.DataFrame(data)[["localTradedAt","closePrice"]]

In [28]:
df=stock_price(30,2)

In [29]:
df

   localTradedAt closePrice
0     2022-06-22   2,342.81
1     2022-06-21   2,408.93
2     2022-06-20   2,391.03
3     2022-06-17   2,440.93
4     2022-06-16   2,451.41
5     2022-06-15   2,447.38
6     2022-06-14   2,492.97
7     2022-06-13   2,504.51
8     2022-06-10   2,595.87
9     2022-06-09   2,625.44
10    2022-06-08   2,626.15
11    2022-06-07   2,626.34
12    2022-06-03   2,670.65
13    2022-06-02   2,658.99
14    2022-05-31   2,685.90
15    2022-05-30   2,669.66
16    2022-05-27   2,638.05
17    2022-05-26   2,612.45
18    2022-05-25   2,617.22
19    2022-05-24   2,605.87
20    2022-05-23   2,647.38
21    2022-05-20   2,639.29
22    2022-05-19   2,592.34
23    2022-05-18   2,625.98
24    2022-05-17   2,620.44
25    2022-05-16   2,596.58
26    2022-05-13   2,604.24
27    2022-05-12   2,550.08
28    2022-05-11   2,592.27
29    2022-05-10   2,596.56

### Quiz1
#### KOSDAQ 데이터 수집 코드 작성

In [33]:
#1. 웹서비스 분석 : URL
url="https://m.stock.naver.com/api/index/KOSDAQ/price?pageSize=10&page=2"
#2. request(url)-> repsonse(json)
response2=requests.get(url)
#3. json -> list, dict -> dataframe
data2=response2.json()
df2=pd.DataFrame(data2)[["localTradedAt","closePrice"]]

In [34]:
df2

  localTradedAt closePrice
0    2022-07-20     790.72
1    2022-07-19     782.33
2    2022-07-18     776.72
3    2022-07-15     762.39
4    2022-07-14     766.08
5    2022-07-13     763.18
6    2022-07-12     750.78
7    2022-07-11     767.04
8    2022-07-08     766.48
9    2022-07-07     757.97

In [ ]:
stock_price(10,1,"KOSDAQ")

In [36]:
kospi=stock_price(60,1)
kosdaq=stock_price(60,1,"KOSDAQ")

In [38]:
#docstring  : 함수를 사용하는 방법을 문자열로 작성
help(stock_price)

Help on function stock_price in module __main__:

stock_price(pagesize, page, code='KOSPI')
    This function is crawling stock price from webpage.
    Param
    ------
    pagesize : int , one page size
    page : int, page number
    code : string, kospi or kosdaq

    Return
    ------
    type : Dataframe, display date, price columns

#### 원달러 환율 데이터 수집
증권 -> 시장지표 -> 미국 USD -> 일별시세(더보기) -> 개발자 도구  
최근 60일치 원달러 환율 데이터 수집

In [52]:
def usd(page,pagesize):
    url3=f"https://api.stock.naver.com/marketindex/exchange/FX_USDKRW/prices?page={page}&pageSize={pagesize}"
    response3=requests.get(url3)
    usd=response3.json()
    usd=pd.DataFrame(usd)[["localTradedAt","closePrice"]]
    return usd

In [62]:
usd=usd(1,60)

### 간단한 데이터 분석
상관관계분석 : 두 데이터 집합 사이에 어떤 관계가 있는 확인하는 분석 방법
ex) 원달러 환율이 높으면 코스피, 코스닥 주가 지수가 낮다. -> 음의 상관관례를 갖는다.

#### 피어슨 상관계수 : df.corr()
-> 결과가 1과 가까울수록 강한 양의 상관관계를 갖는다.
-1 과 가까울수록 강한 음의 상관계수를 갖는다.
0과 가까울수록 관계가 없다.

In [93]:
# 데이터 전처리
df=kospi.copy()
df["kosdaq"]=kosdaq["closePrice"]
df["usd"]=usd["closePrice"]
df=df.rename(columns={"closePrice":"kospi"})
df.tail(2)

   localTradedAt     kospi  kosdaq       usd
58    2022-05-11  2,592.27  866.34  1,274.50
59    2022-05-10  2,596.56  856.14  1,276.00

In [94]:
df.dtypes

localTradedAt    object
kospi            object
kosdaq           object
usd              object
dtype: object

In [95]:
#데이터 타입 float로 변경
#df[column].apply() : 모든 데이터를 함수에 대입한 결과를 출력
df['kospi']=df['kospi'].apply(lambda data: float(data.replace(",",""))) # , 제거후 형 변환
df['usd']=df['usd'].apply(lambda data: float(data.replace(",","")))
df['kosdaq']=df['kosdaq'].apply(lambda data: float(data.replace(",","")))

In [96]:
# kospi - kosdaq : 0.984 -> 1과 가까우며 강한 양의 상관관계
# kospi - usd : -0.878 : -1과 가까우며 강한 음의 상관관계
df[['kospi', 'kosdaq', 'usd']].corr()

           kospi    kosdaq       usd
kospi   1.000000  0.984042 -0.878452
kosdaq  0.984042  1.000000 -0.821439
usd    -0.878452 -0.821439  1.000000

### pandas add

#### copy()

In [79]:
# copy() -> copy를 사용해야 원본 수정 에러 X
d1=[1,2,3]
d2=d1
print(d1,d2) #[1, 2, 3] [1, 2, 3]
d1[1]=4
print(d1,d2) #[1, 4, 3] [1, 4, 3]

[1, 2, 3] [1, 2, 3]
[1, 4, 3] [1, 4, 3]

In [80]:
d1=[1,2,3]
d2=d1 #주소값 복사 -> 얕은 복사 (call by reference)
d3=d1.copy() #값복사 -> 깊은 복사 (call by value)
print(d1,d2,d3) #[1, 2, 3] [1, 2, 3] [1, 2, 3]
d1[1]=4
print(d1,d2,d3) #[1, 4, 3] [1, 4, 3] [1, 2, 3]

[1, 2, 3] [1, 2, 3] [1, 2, 3]
[1, 4, 3] [1, 4, 3] [1, 2, 3]

#### apply(func)
모든 데이터를 func을 적용시킨 결과 출력

In [81]:
#apply(func) : 모든 데이터를 func을 적용시킨 결과 출력
df=pd.DataFrame([
    {"age":23},{"age":36},{"age":27}
])
df

   age
0   23
1   36
2   27

In [82]:
# 연령대 컬럼 추가
def change_ages(age):
    return age // 10*10

In [86]:
df["ages"]=df["age"].apply(change_ages)
df

   age  ages
0   23    20
1   36    30
2   27    20

#### lambda : 일회성함수
사용하는 이유 -> 간단한 함수(파라미터를 받아서 바로 리턴하는)를 메모리를 절약하여 사용가능

In [87]:
#함수 3개 사용, 메모리 3칸 사용
def plus(n1,n2):
    return n1+n2
def minus(n1,n2):
    return n1-n2
def calc(func,n1,n2):
    return func(n1,n2)

In [90]:
calc(plus,1,2),calc(minus,1,2)

(3, -1)

In [91]:
plus_lambda=lambda n1,n2 : n1+n2
plus(2,3), plus_lambda(2,3)

(5, 5)

In [92]:
def calc(func,n1,n2):
    return func(n1,n2)
calc(lambda n1,n2: n1+n2,1,2), calc(lambda n1,n2: n1-n2,1,2)

(3, -1)

### Summary
웹페이지 종류
1. 정적페이지 : 데이터가 변경될떄 URL 변경 O -> HTML
2. 동적페이지 : 데이터가 변경될때 URL 변경 X -> JSON

동적 웹크롤링 절차
1. 웹서비스 분석 : 크롬 개발자 도구 -> URL
2. request(url) -> response(json) -> json(str)
3. json(str) -> list, dict -> dataframe